---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-users.html 
summary: Elenca tutti gli utenti 
---
= Elenca tutti gli utenti
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users`#

Restituisce un array JSON di tutte le risorse corrispondenti nella raccolta. Se nella richiesta vengono specificati singoli campi, l'array JSON degli elementi conterrà i campi richiesti per ciascuna risorsa corrispondente nell'ordine specificato.



[[parameters]]
== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| includi | stringa | query | Falso  a| 
Indica quali campi devono essere restituiti durante l'elenco di una raccolta.

Esempi di URL: "include=id", "include=id,name"

Esempi OpenAPI: "id"

* esempio: id,email




| limite | stringa | query | Falso  a| 
Indica il numero massimo di risorse da restituire quando si elenca una raccolta.

Esempi di URL: "limit=2"

Esempi OpenAPI: "2"



| filtro | stringa | query | Falso  a| 
Indica quali campi devono essere confrontati per restituire una risorsa durante l'elenco di una collezione.

Gli operatori supportati sono:

* eq - Uguaglianza
* lt/gt - Minore di/Maggiore di
* lte/gte - Minore o uguale a/Maggiore o uguale a


Esempio di URL: "filter=field%20eq%20%27value%27"

Esempi OpenAPI: "field eq 'value'"



| OrderBy | stringa | query | Falso  a| 
Indica l'ordine di visualizzazione delle risorse durante l'elenco di una collezione.

Esempi di URL: "orderBy=name", "orderBy=name%20desc"

Esempi OpenAPI: "name desc"



| saltare | stringa | query | Falso  a| 
Indica il numero di risorse da saltare durante l'elenco di una raccolta.

Esempi di URL: "skip=1"

Esempi OpenAPI: "1"



| conta | stringa | query | Falso  a| 
Indica se il numero totale di risorse deve essere restituito nell'oggetto metadata.

Esempi di URL: "count=true"

Esempi OpenAPI: "true"



| continuare |  | query | Falso  a| 
Indica il token da cui riprendere l'elenco.

Esempi di URL: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

Esempi OpenAPI: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


[[response]]
== Risposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| elementi | array[Qualsiasi tra: link:#user_1_2_get_response_body["user_1.2_get_response_body"], array[]] | Vero  a| 



| metadati | link:#type_astra_metadata_list["elenco_metadati_tipo_astra"] | Vero  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-users",
  "version": "1.2",
  "items": [
    [
      "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa",
      "jdoe@example.com"
    ],
    [
      "e324ec3a-706d-4f57-a95d-1d88c03e7b73",
      "ssmith@example.com"
    ],
    [
      "3070c84d-129b-4017-82a8-2c26a42dd77e",
      "wjohns@example.com"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Definizioni

.Vedi definizioni
[%collapsible]
====
[[postalAddress]]
[role="api-collapsible-fifth-title"]
postalAddress

Oggetto JSON contenente una raccolta di campi che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutti e sei i campi contenuti. Se non è stato fornito nulla dall'utente, la stringa sarà vuota.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| addressCountry | stringa | Vero  a| 
Stringa JSON contenente il nome o il codice del paese associato all'indirizzo postale, come specificato nello standard ISO 3166 Alpha-2. I valori definiti sono:

* Lunghezza minima: 2
* Lunghezza massima: 2




| addressLocality | stringa | Vero  a| 
Stringa JSON contenente la località (ad esempio, la città) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| addressRegion | stringa | Vero  a| 
Stringa JSON contenente la regione (ad esempio, stato) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| postalCode | stringa | Vero  a| 
Stringa JSON contenente il codice postale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| streetAddress1 | stringa | Vero  a| 
Stringa JSON contenente l'indirizzo stradale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| streetAddress2 | stringa | Falso  a| 
Stringa JSON contenente informazioni aggiuntive facoltative sull'indirizzo stradale, casella postale e così via. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63


|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[user_1_2_get_response_body]]
[role="api-collapsible-fifth-title"]
user_1.2_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-user"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"
* "1,2"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| stato | stringa | Vero  a| 
Stringa JSON contenente un valore che indica lo stato operativo dell'utente. I valori definiti sono:

* "in sospeso" - L'account utente è in fase di creazione. L'utente può solo leggere e modificare la risorsa utente (valore predefinito).
* Questo stato non è valido per un utente con "authProvider" come "local"
* "attivo" - L'account utente è operativo (l'utente può accedere se l'impostazione dell'account "isEnabled" è "true").
* Questo è il valore predefinito per un utente con "authProvider" come "local"
* "sospeso" - L'account utente è sospeso (l'utente non può accedere indipendentemente dall'impostazione "isEnabled" dell'account).




| isEnabled | stringa | Vero  a| 
Stringa JSON che indica se l'utente è autorizzato ad accedere. I valori definiti sono:

* "true" - L'utente è autorizzato ad accedere; valore predefinito alla creazione.
* "false" - L'utente non è autorizzato ad accedere.




| authID | stringa | Falso  a| 
Stringa JSON contenente l'identificativo associato a un provider di identità esterno. Il contenuto di questa stringa dipende da quanto specificato authProvider. Per un utente con "authProvider" come "local", "authID" è impostato sul valore di "email". Per un utente con "authProvider" come "ldap", "authID" è impostato sul suo Distinguished Name (DN) dal LDAP server.



| authProvider | stringa | Falso  a| 
Stringa JSON che indica il contesto dell'identificatore idAuth. I valori definiti sono:

* "cloud-central" - L'autenticazione dell'utente proviene dal servizio NetApp Cloud Central
* "locale" - L'autenticazione dell'utente proviene dall'archivio locale di utenti/password
* "ldap" - L'autenticazione dell'utente proviene da un LDAP server. In Astra Control Center, tutti gli utenti devono avere un valore "local" o "ldap". Se non viene specificato un valore, viene scelto il valore predefinito "local". In Astra Control Service, "authProvider" come "local" o "ldap" non è supportato. Se non viene specificato un valore, verrà utilizzato il valore predefinito "cloud-central".




| firstName | stringa | Vero  a| 
Stringa JSON contenente un nome proprio lungo specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| lastName | stringa | Vero  a| 
Stringa JSON contenente un cognome esteso specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| companyName | stringa | Falso  a| 
Stringa JSON contenente il nome dell'azienda associata all'utente. Se questa chiave non esiste, significa che non è stato fornito un nome di azienda. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| email | stringa | Vero  a| 
Stringhe JSON contenenti un indirizzo email specificato dall'utente.



| telefono | stringa | Falso  a| 
Stringa JSON contenente il numero di telefono dell'utente. Se questa chiave non esiste, significa che non è stato fornito un numero di telefono.



| postalAddress | link:#postalAddress["postalAddress"] | Falso  a| 
Oggetto JSON contenente una raccolta di campi che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutti e sei i campi contenuti. Se non è stato fornito nulla dall'utente, la stringa sarà vuota.



| sendWelcomeEmail | stringa | Vero  a| 
Stringa JSON che indica se verrà inviata un'e-mail di benvenuto dopo la convalida. Se non specificato in fase di creazione, il valore verrà impostato su "true" per ACS e su "false" per Astra Control Center. I valori definiti sono:

* "true" - Verrà inviata un'e-mail di benvenuto; valore predefinito alla creazione
* "false" - Non verrà inviata alcuna email di benvenuto Per un utente con "authProvider" come "local" o "ldap", questo valore viene ignorato e impostato su "false".




| enableTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp in formato ISO-8601 che indica quando l'utente è stato abilitato per l'ultima volta. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| lastActTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp in formato ISO-8601 che indica quando l'API di identità è stata invocata l'ultima volta per conto di questo utente. (Nota: questa operazione è dispendiosa in termini di risorse.) I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
elenco_metadati_tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| continuare | stringa | Falso  a| 



| conta | numero | Falso  a| 



| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====