---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-credentials.html 
summary: Elenca tutte le credenziali 
---
= Elenca tutte le credenziali
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials`#

Restituisce un array JSON di tutte le risorse corrispondenti nella raccolta. Se nella richiesta vengono specificati singoli campi, l'array JSON degli elementi conterrà i campi richiesti per ciascuna risorsa corrispondente nell'ordine specificato.



== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| continuare |  | query | Falso  a| 
Indica il token da cui riprendere l'elenco.

Esempi di URL: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

Esempi OpenAPI: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>



| filtro | stringa | query | Falso  a| 
Indica quali campi devono essere confrontati per restituire una risorsa durante l'elenco di una collezione.

Gli operatori supportati sono:

* eq - Uguaglianza
* lt/gt - Minore di/Maggiore di
* lte/gte - Minore o uguale a/Maggiore o uguale a


Esempio di URL: "filter=field%20eq%20%27value%27"

Esempi OpenAPI: "field eq 'value'"



| includi | stringa | query | Falso  a| 
Indica quali campi devono essere restituiti durante l'elenco di una raccolta.

Esempi di URL: "include=id", "include=id,name"

Esempi OpenAPI: "id"

* esempio: id,nome




| limite | stringa | query | Falso  a| 
Indica il numero massimo di risorse da restituire quando si elenca una raccolta.

Esempi di URL: "limit=2"

Esempi OpenAPI: "2"



| OrderBy | stringa | query | Falso  a| 
Indica l'ordine di visualizzazione delle risorse durante l'elenco di una collezione.

Esempi di URL: "orderBy=name", "orderBy=name%20desc"

Esempi OpenAPI: "name desc"

|===


== Risposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| elementi | array[Qualsiasi tra: link:#credential_1_1_get_response_body["credential_1.1_get_response_body"], array[]] | Vero  a| 



| metadati | link:#type_astra_metadata_list["elenco_metadati_tipo_astra"] | Vero  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credentials",
  "version": "1.1",
  "items": [
    [
      "f97f3441-075e-4f9b-9d1e-47f9f62a3fc4",
      "myCert"
    ],
    [
      "5e365b4d-034f-4f13-95ef-d3a7fbc0df3d",
      "kubeconfig"
    ],
    [
      "11ceb350-1999-4b79-80a6-46a980a27856",
      "password"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
credential_1.1_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-credential"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Vero  a| 
Stringa JSON contenente un nome specificato dall'utente. Quando viene creata una credenziale per un utente, il nome verrà impostato sull'UUID di tale utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 127




| keyType | stringa | Falso  a| 
Stringa JSON contenente un descrittore del tipo di convalida dei dati facoltativo specificato dall'utente per il contenuto di keyStore. Vincoli di aggiornamento estesi:

* Se un elemento keyType non esiste nella risorsa e non è specificato in un aggiornamento, il keyType non deve continuare a esistere nella risorsa aggiornata.
* Se un keyType non esiste nella risorsa ed è specificato in un aggiornamento, il keyType deve essere aggiunto alla risorsa ed è necessario eseguire la convalida. Se la convalida fallisce, l'aggiornamento fallirà.
* Se un keyType esiste nella risorsa e non è specificato in un aggiornamento, il keyType deve essere conservato.
* Se un keyType esiste nella risorsa ed è specificato in un aggiornamento, e il keyType specificato corrisponde al keyType esistente, il keyType deve essere conservato.
* Se un keyType esiste nella risorsa ed è specificato in un aggiornamento, e il keyType specificato è diverso dall'esistente keyType, l'aggiornamento non andrà a buon fine. I valori definiti sono:
* "generico" - La credenziale è una raccolta generica di dati. Ciò equivale a non includere un keyType.
* La convalida estesa viene eseguita come segue:
* Una o più stringhe devono esistere nel keyStore.
* Ogni stringa nel keyStore deve avere un valore codificato in base64.
* "passwordHash" - La credenziale è un hash della password.
* La convalida estesa viene eseguita come segue:
* Il nome della credenziale deve essere univoco.
* Il nome della credenziale deve corrispondere a un ID risorsa utente valido.
* Il nome della credenziale non deve essere modificato.
* La risorsa utente corrispondente deve avere un "authProvider" di "local".
* Deve essere presente una stringa "in chiaro" all'interno del keyStore con un valore contenente una password in chiaro codificata in base64:
* La password in chiaro deve essere conforme alla policy relativa alle password dell'account.
* La password viene memorizzata come hash.
* All'interno del keyStore deve essere presente una stringa "change" con un valore contenente una stringa codificata in base64 "true" o "false".
* Una credenziale di tipo passwordHash può essere eliminata solo se l'ID utente indicato dal nome non esiste.
* "apikey" - La credenziale è una chiave API.
* La convalida estesa viene eseguita come segue:
* Una stringa "apikey" deve esistere all'interno del keyStore, con un valore contenente una stringa arbitraria codificata in base64.
* "kubeconfig" - La credenziale è un kubeconfig.
* La convalida estesa viene eseguita come segue:
* All'interno del keyStore deve essere presente una stringa "base64" con un valore contenente un file kubeconfig JSON codificato in base64.
* Il file kubeconfig deve descrivere un solo cluster.
* Non possono esistere altri campi all'interno del keyStore.
* "certificato" - La credenziale è un certificato codificato in formato PEM
* La convalida estesa viene eseguita come segue:
* All'interno di keyStore deve essere presente una stringa "certificate" con un valore contenente un certificato PEM codificato in base64.
* "privkey" - La credenziale è una chiave privata codificata in formato PEM.
* La convalida estesa viene eseguita come segue:
* All'interno del keyStore deve essere presente una stringa "privkey", con un valore contenente una chiave privata PEM codificata in base64.
* "s3" - Indica che le credenziali sono per l'accesso al servizio Simple Storage Service (S3).
* La convalida estesa viene eseguita come segue:
* Una stringa ""accessKey"" deve esistere all'interno del keyStore con un valore contenente una chiave di accesso S3 codificata in base64.
* Una stringa ""accessSecret"" deve esistere all'interno del keyStore con un valore contenente un segreto di accesso S3 codificato in base64.




| valido | stringa | Vero  a| 
Stringa JSON che descrive se la credenziale è valida per l'uso. Il valore predefinito, se omesso, è "true". I valori definiti sono:

* "vero" - La credenziale è idonea all'uso.
* "falso" - La credenziale non deve essere utilizzata.




| validFromTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando la credenziale è valida. Queste vengono utilizzate per la rotazione delle credenziali. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| validUntilTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando la credenziale non è più valida. Queste vengono utilizzate per la rotazione delle credenziali. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
[role="api-collapsible-fifth-title"]
elenco_metadati_tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| continuare | stringa | Falso  a| 



| conta | numero | Falso  a| 



| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====