---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-.html 
summary: Recupera un account 
---
= Recupera un account
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}`#

Restituisce la risorsa API Account memorizzata nel corpo della risposta JSON.



[[parameters]]
== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della raccolta di account da elencare

* esempio: {{.Account}}


|===


[[response]]
== Risposta

[source]
----
Status: 200, Returns the stored Account API resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-account"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Vero  a| 
Stringa JSON contenente il nome dell'account. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.




| stato | stringa | Vero  a| 
Stringa JSON contenente un valore che indica lo stato operativo dell'account. I valori definiti sono:

* "in sospeso" - Le modifiche possono essere apportate solo alle risorse utente e ruolo dell'account (valore predefinito)
* "attivo" - È possibile apportare modifiche a qualsiasi risorsa dell'account
* "deletePending" - Gli utenti non possono accedere, le operazioni di protezione dei dati sono sospese, gli addebiti non maturano più




| isEnabled | stringa | Vero  a| 
Stringa JSON che indica che l'account è abilitato. I valori definiti sono:

* "falso" - Gli utenti non sono autorizzati a utilizzare questo account
* "vero" - Gli utenti sono autorizzati a utilizzare questo account




| enabledTimestamp | stringa | Falso  a| 
Stringa JSON contenente il timestamp che indica quando l'account è stato abilitato per l'ultima volta. Se l'account non è mai stato abilitato, questo campo è assente. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| accountContact | link:#accountContact["accountContact"] | Falso  a| 
Oggetto JSON contenente le informazioni di contatto dell'utente per creare un utente proprietario al momento dell'attivazione dell'account.



| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-account",
  "version": "1.0",
  "id": "666a3f38-d4fa-5b62-a391-a69029758d32",
  "name": "fraught-pines",
  "state": "active",
  "isEnabled": "true",
  "enabledTimestamp": "2020-08-06T12:24:52.256624Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Definizioni

.Vedi definizioni
[%collapsible]
====
[[postalAddress]]
[role="api-collapsible-fifth-title"]
postalAddress

Oggetto JSON contenente una raccolta di stringhe JSON che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutte e sei le stringhe JSON contenute. Se non si fornisce nulla, la stringa sarà vuota.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| addressCountry | stringa | Vero  a| 
Stringa JSON contenente il nome o il codice del paese associato all'indirizzo postale, come specificato nello standard ISO 3166 Alpha-2. I valori definiti sono:

* Lunghezza minima: 2
* Lunghezza massima: 2




| addressLocality | stringa | Vero  a| 
Stringa JSON contenente la località (ad esempio, la città) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| addressRegion | stringa | Vero  a| 
Stringa JSON contenente la regione (ad esempio, stato) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| postalCode | stringa | Vero  a| 
Stringa JSON contenente il codice postale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| streetAddress1 | stringa | Vero  a| 
Stringa JSON contenente l'indirizzo stradale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| streetAddress2 | stringa | Falso  a| 
Stringa JSON contenente informazioni aggiuntive facoltative sull'indirizzo stradale, casella postale e altro. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63


|===
[[accountContact]]
[role="api-collapsible-fifth-title"]
accountContact

Oggetto JSON contenente le informazioni di contatto dell'utente per creare un utente proprietario al momento dell'attivazione dell'account.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| firstName | stringa | Vero  a| 
Stringa JSON contenente un nome proprio lungo specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.




| lastName | stringa | Vero  a| 
Stringa JSON contenente un cognome esteso specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.




| companyName | stringa | Falso  a| 
Stringa JSON contenente il nome dell'azienda associata all'utente. Se questa chiave non esiste, significa che non è stato fornito un nome di azienda. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.




| email | stringa | Vero  a| 
Stringhe JSON contenenti un indirizzo email specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| telefono | stringa | Falso  a| 
Stringa JSON contenente il numero di telefono dell'utente. Se questa chiave non esiste, significa che non è stato fornito un numero di telefono. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| postalAddress | link:#postalAddress["postalAddress"] | Vero  a| 
Oggetto JSON contenente una raccolta di stringhe JSON che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutte e sei le stringhe JSON contenute. Se non si fornisce nulla, la stringa sarà vuota.

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====