---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-subscriptions.html 
summary: Elenca tutti gli abbonamenti 
---
= Elenca tutti gli abbonamenti
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/subscriptions`#

Restituisce un array JSON di tutte le risorse corrispondenti nella raccolta. Se nella richiesta vengono specificati singoli campi, l'array JSON degli elementi conterrà i campi richiesti per ciascuna risorsa corrispondente nell'ordine specificato.



== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| continuare |  | query | Falso  a| 
Indica il token da cui riprendere l'elenco.

Esempi di URL: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

Esempi OpenAPI: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>



| conta | stringa | query | Falso  a| 
Indica se il numero totale di risorse deve essere restituito nell'oggetto metadata.

Esempi di URL: "count=true"

Esempi OpenAPI: "true"



| filtro | stringa | query | Falso  a| 
Indica quali campi devono essere confrontati per restituire una risorsa durante l'elenco di una collezione.

Gli operatori supportati sono:

* eq - Uguaglianza
* lt/gt - Minore di/Maggiore di
* lte/gte - Minore o uguale a/Maggiore o uguale a


Esempio di URL: "filter=field%20eq%20%27value%27"

Esempi OpenAPI: "field eq 'value'"



| includi | stringa | query | Falso  a| 
Indica quali campi devono essere restituiti durante l'elenco di una raccolta.

Esempi di URL: "include=id", "include=id,name"

Esempi OpenAPI: "id"



| limite | stringa | query | Falso  a| 
Indica il numero massimo di risorse da restituire quando si elenca una raccolta.

Esempi di URL: "limit=2"

Esempi OpenAPI: "2"



| OrderBy | stringa | query | Falso  a| 
Indica l'ordine di visualizzazione delle risorse durante l'elenco di una collezione.

Esempi di URL: "orderBy=name", "orderBy=name%20desc"

Esempi OpenAPI: "name desc"



| saltare | stringa | query | Falso  a| 
Indica il numero di risorse da saltare durante l'elenco di una raccolta.

Esempi di URL: "skip=1"

Esempi OpenAPI: "1"

|===


== Risposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| elementi | array[Qualsiasi tra: link:#subscription_1_2_get_response_body["subscription_1.2_get_response_body"], array[]] | Vero  a| 



| metadati | link:#type_astra_metadata_list["elenco_metadati_tipo_astra"] | Vero  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-subscriptions",
  "version": "1.2",
  "items": [
    {
      "type": "application/astra-subscription",
      "version": "1.1",
      "id": "d4c865c9-64a7-4661-ae4a-3307dffcd3da",
      "customerProfileID": "2157047189",
      "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
      "paymentExpiry": "2022-02-01T00:00:00Z",
      "purchaseOrderNumber": "72384632",
      "marketplace": "netapp",
      "licenseSN": "278343",
      "terms": "trial",
      "status": "inactive",
      "appLimit": 0,
      "namespaceLimit": 10,
      "subscriptionPeriod": 90,
      "gracePeriod": 7,
      "reminderBeforePeriod": 30,
      "onboardStatus": "success",
      "costPerAppUnit": 0,
      "costPerNamespaceUnit": 0.005,
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-05-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-05-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    },
    {
      "type": "application/astra-subscription",
      "version": "1.1",
      "id": "4c43ed8b-078f-4fe3-b8c6-5d515f6382e6",
      "customerProfileID": "2157047189",
      "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
      "paymentExpiry": "2022-05-01T00:00:00Z",
      "purchaseOrderNumber": "92374658",
      "marketplace": "netapp",
      "licenseSN": "374623",
      "terms": "paid",
      "status": "active",
      "appLimit": 0,
      "namespaceLimit": -1,
      "subscriptionPeriod": -1,
      "gracePeriod": -1,
      "reminderBeforePeriod": -1,
      "onboardStatus": "success",
      "costPerAppUnit": 0,
      "costPerNamespaceUnit": 0.005,
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
subscription_1.2_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-subscription"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"
* "1,2"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| customerProfileID | stringa | Vero  a| 
La stringa JSON contenente l'ID del profilo del cliente da  http://authorize.net["Authorize.net"], che è stata richiamata dall'interfaccia utente, non è impostata per il periodo di prova. Restituisce una stringa vuota durante l'operazione di lettura, se non impostata. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63




| paymentProfileID | stringa | Falso  a| 
Stringa JSON contenente l'ID del profilo di pagamento da  http://Authorize.net["Authorize.net"] che è stato richiamato dall'interfaccia utente, non impostato per il grace period. Restituisce una stringa vuota durante l'operazione di lettura se non impostato. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63




| paymentExpiry | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando il metodo di pagamento scade. Questo è ottenuto da authorize.net(http://authorize.net[] e viene impostato dall'interfaccia utente. I valori definiti sono:

* Conforme allo schema data/ora ISO-8601 Questo campo non viene restituito per i periodi di prova.




| purchaseOrderNumber | stringa | Falso  a| 
Stringa JSON contenente il numero dell'ordine di acquisto per il metodo di pagamento. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| marketplace | stringa | Falso  a| 
Stringa JSON che indica il marketplace per un account in cui verranno registrati i pagamenti. Valori definiti:

* "netapp"
* "azure"
* "aws"
* "gcp"




| licenseSN | stringa | Falso  a| 
Stringa JSON contenente il numero di serie della licenza per il metodo di pagamento. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| termini | stringa | Vero  a| 
Stringa JSON che indica il livello attuale dell'account. I valori definiti sono:

* "prova"
* "pagato"




| stato | stringa | Vero  a| 
Stringa JSON che indica lo stato attuale dell'abbonamento. I valori definiti sono:

* "attivo"
* "inattivo"




| appLimit | numero | Vero  a| 
Numero JSON che indica il limite di applicazioni per questo abbonamento. Il valore -1 indica nessun limite.



| namespaceLimit | numero | Vero  a| 
Numero JSON che indica il limite di namespace per questo abbonamento. Il valore -1 indica nessun limite.



| subscriptionPeriod | numero | Vero  a| 
Numero JSON che indica il periodo di abbonamento. Il valore -1 indica nessun limite. Unità: giorni



| gracePeriod | numero | Vero  a| 
Numero JSON che indica il grace period successivo alla scadenza del periodo di prova o all'annullamento di un abbonamento a pagamento. Unità: giorni



| reminderBeforePeriod | numero | Vero  a| 
Numero JSON che indica il numero di giorni prima della fine del periodo di prova in cui inizieranno le notifiche al cliente. Il valore è espresso in giorni con un valore di -1 che indica che non è applicabile.



| onboardStatus | stringa | Vero  a| 
Stringa JSON che indica lo stato attuale dell'onboarding del cliente. I valori validi sono "non avviato", "in corso", "riuscito", "fallito". I valori definiti sono:

* "non avviato"
* "in corso"
* "successo"
* "fallito"




| costPerAppUnit | numero | Vero  a| 
Numero JSON che indica il costo per unità dell'app. Per la versione di prova, il valore è 0. Unità: dollari statunitensi



| costPerNamespaceUnit | numero | Vero  a| 
Numero JSON che indica il costo per unità di namespace. Per la versione di prova, il valore è 0. Unità: dollari statunitensi



| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
[role="api-collapsible-fifth-title"]
elenco_metadati_tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| continuare | stringa | Falso  a| 



| conta | numero | Falso  a| 



| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====