---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-schedules.html 
summary: 'Elenca le pianificazioni per un"app' 
---
= Elenca le pianificazioni per un'app
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/schedules`#

Restituisce un array JSON di tutte le risorse corrispondenti nella raccolta. Se nella richiesta vengono specificati singoli campi, l'array JSON degli elementi conterrà i campi richiesti per ciascuna risorsa corrispondente nell'ordine specificato.



== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| app_id | stringa | percorso | Vero  a| 
ID della risorsa dell'app che la contiene



| includi | stringa | query | Falso  a| 
Indica quali campi devono essere restituiti durante l'elenco di una raccolta.

Esempi di URL: "include=id", "include=id,name"

Esempi OpenAPI: "id"

* esempio: id,nome,granularità




| limite | stringa | query | Falso  a| 
Indica il numero massimo di risorse da restituire quando si elenca una raccolta.

Esempi di URL: "limit=2"

Esempi OpenAPI: "2"

|===


== Risposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| elementi | array[Qualsiasi tra: link:#schedule_1_3_get_response_body["schedule_1.3_get_response_body"], array[]] | Vero  a| 



| metadati | link:#type_astra_metadata_list["elenco_metadati_tipo_astra"] | Vero  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-schedules",
  "version": "1.3",
  "items": [
    [
      "0d6d20d6-8b7c-498a-b57b-5734210c209a",
      "Backup Schedule",
      "monthly"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
schedule_1.3_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-schedule"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Vero  a| 
Stringa JSON contenente il nome della pianificazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| abilitato | stringa | Vero  a| 
Stringa JSON che indica se una pianificazione è attiva. I valori definiti sono:

* "vero" - La pianificazione è attiva
* "false" - La pianificazione non è attiva Se non specificato, il valore predefinito è "true".




| granularità | stringa | Vero  a| 
Stringa JSON che indica la granularità della pianificazione. I valori definiti sono:

* "ogni ora"
* "quotidiano"
* "settimanale"
* "mensile"
* "personalizzato"




| minuto | stringa | Vero  a| 
Stringa JSON contenente un valore numerico che indica il minuto dell'ora (0 - 59) in cui eseguire la pianificazione. I valori definiti sono:

* L'espressione regolare definita è: "^[0-9]|[1-5][0-9]$" Questo campo è presente se la granularità è impostata su "oraria", "giornaliera", "settimanale" o "mensile". Verrà restituito con il valore "0" per le pianificazioni personalizzate.




| ora | stringa | Falso  a| 
Stringa JSON contenente un valore numerico che indica l'ora del giorno (0 - 23) in cui eseguire la pianificazione. I valori definiti sono:

* L'espressione regolare definita è: "^[0-9]|[1][0-9]|[2][0-3]$" Questo campo è presente se la granularità è impostata su "giornaliera", "settimanale" o "mensile".




| dayOfWeek | stringa | Falso  a| 
Stringa JSON contenente un valore numerico che indica il giorno della settimana (0-7) in cui eseguire la pianificazione. I valori definiti sono:

* L'espressione regolare definita è: "^[0-7]$" Questo campo è presente solo se la granularità è impostata su "weekly".




| dayOfMonth | stringa | Falso  a| 
Stringa JSON contenente un valore numerico che indica il giorno del mese (1-31) in cui eseguire la pianificazione. I valori definiti sono:

* L'espressione regolare definita è: "^[1-9]|[1-2][0-9]|[3][0-1]$" Questo campo è presente solo se la granularità è impostata su "mensile".




| recurrenceRule | stringa | Falso  a| 
Stringa JSON contenente una sezione 3.8.5.3 dell'RFC-5545. Regola di ricorrenza. Per il parametro DTSTART, sono supportati solo i timestamp UTC (indicati dal suffisso "Z") e solo i timestamp precedenti all'ora corrente. Per le parti della regola RECUR, sono supportate solo le parti "FREQ" e "INTERVAL". Per la parte della regola FREQ, sono supportati solo i valori "MINUTELY" e "HOURLY". Questo campo è presente solo se la granularità è impostata su "custom".



| snapshotRetention | stringa | Vero  a| 
Stringa JSON contenente un valore numerico positivo che indica quanti snapshot conservare. Zero indica che gli snapshot devono essere eliminati dopo aver effettuato un backup. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* L'espressione regolare definita è: "^(0|([1-9][0-9]*))$"




| backupRetention | stringa | Vero  a| 
Stringa JSON contenente un valore numerico positivo che indica quanti backup conservare. Zero indica che non devono essere creati backup. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* L'espressione regolare definita è: "^(0|([1-9][0-9]*))$"




| bucketID | stringa | Falso  a| 
Stringa JSON contenente un ID bucket facoltativo che indica dove deve essere archiviato il backup al momento della creazione. Se non specificato, verrà utilizzato un bucket selezionato dal sistema. I valori definiti sono:

* Conforme allo schema identificativo Astra




| replicare | stringa | Falso  a| 
Stringa JSON che indica se la pianificazione attiva la replica AppMirror per ogni snapshot. Ha effetto solo se l'applicazione ha una relazione AppMirror definita. I valori definiti sono:

* "vero" - La pianificazione attiva la replica AppMirror
* "false" - La pianificazione non attiva la replica AppMirror. Se non specificato, il valore predefinito è "false".




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
[role="api-collapsible-fifth-title"]
elenco_metadati_tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| continuare | stringa | Falso  a| 



| conta | numero | Falso  a| 



| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====