---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-licenses.html 
summary: Elenca tutte le licenze 
---
= Elenca tutte le licenze
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/licenses`#

Restituisce un array JSON di tutte le risorse corrispondenti nella raccolta. Se nella richiesta vengono specificati singoli campi, l'array JSON degli elementi conterrà i campi richiesti per ciascuna risorsa corrispondente nell'ordine specificato.



[[parameters]]
== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| includi | stringa | query | Falso  a| 
Indica quali campi devono essere restituiti durante l'elenco di una raccolta.

Esempi di URL: "include=id", "include=id,name"

Esempi OpenAPI: "id"

* esempio: id,prodotto




| limite | stringa | query | Falso  a| 
Indica il numero massimo di risorse da restituire quando si elenca una raccolta.

Esempi di URL: "limit=2"

Esempi OpenAPI: "2"



| filtro | stringa | query | Falso  a| 
Indica quali campi devono essere confrontati per restituire una risorsa durante l'elenco di una collezione.

Gli operatori supportati sono:

* eq - Uguaglianza
* lt/gt - Minore di/Maggiore di
* lte/gte - Minore o uguale a/Maggiore o uguale a


Esempio di URL: "filter=field%20eq%20%27value%27"

Esempi OpenAPI: "field eq 'value'"

|===


[[response]]
== Risposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| elementi | array[Qualsiasi tra: link:#license_1_0_get_response_body["license_1.0_get_response_body"], array[]] | Vero  a| 



| metadati | link:#type_astra_metadata_list["elenco_metadati_tipo_astra"] | Vero  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-licenses",
  "version": "1.0",
  "items": [
    [
      "c8aa757a-5318-489f-8134-a2a1a6956a3e",
      "Astra SDS"
    ],
    [
      "0f7cc03d-9afc-4192-af7f-b29ab24f8f2a",
      "Astra Enterprise"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Definizioni

.Vedi definizioni
[%collapsible]
====
[[addons]]
[role="api-collapsible-fifth-title"]
componenti aggiuntivi

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| startDate | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando questo componente aggiuntivo diventa valido. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| endDate | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando questo componente aggiuntivo non è più valido. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| caratteristiche | stringa | Falso  a| 
Stringa JSON contenente l'elenco delle funzionalità associate a questo componente aggiuntivo. I valori definiti sono:

* Il contenuto della stringa non è convalidato dallo schema.




| capacità | stringa | Falso  a| 
Stringa JSON contenente la capacità estratta dal componente aggiuntivo. I valori definiti sono:

* Il contenuto della stringa non è convalidato dallo schema




| licenseProtocol | stringa | Falso  a| 
Stringa JSON contenente il protocollo di licenza associato a questo componente aggiuntivo. I valori definiti sono:

* Il contenuto della stringa non è convalidato dallo schema


|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[license_1_0_get_response_body]]
[role="api-collapsible-fifth-title"]
license_1.0_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-license"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| allocazione | stringa | Falso  a| 
Stringa JSON contenente un ID che indica a cosa è assegnata la licenza. Presente solo quando la licenza è assegnata. Per le licenze di Astra Control Center, questo campo deve essere compilato con l'ID dell'account e deve corrispondere all'ID dell'account specificato nell'URI POST. I valori definiti sono:

* Conforme allo schema identificativo Astra




| ID host | stringa | Falso  a| 
Stringa JSON contenente un identificatore host a cui è associata una licenza. Presente solo se la licenza è vincolata a un host. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| ID credenziali del dispositivo | stringa | Falso  a| 
Stringa JSON contenente l'identificativo del deviceCredential associato all'API delle credenziali. Presente solo per le licenze Astra Data Store. I valori definiti sono:

* Conforme allo schema identificativo Astra




| isEvaluation | stringa | Vero  a| 
Stringa JSON che indica se la licenza è una licenza di valutazione. I valori definiti sono:

* "true"
* "false"




| licenseProtocol | stringa | Vero  a| 
Stringa JSON contenente il protocollo di licenza estratto dalla licenza. I valori definiti sono:

* Il contenuto della stringa non è convalidato dallo schema




| licenseText | stringa | Vero  a| 
Stringa JSON contenente una rappresentazione codificata in base64 della licenza JSON ottenuta dal sistema di licenze NetApp. Questa deve essere fornita nell'ordine originale a livello di byte per consentire la verifica della firma. I valori definiti sono:

* Conforme allo schema di dati codificati in base64




| validFromTimestamp | stringa | Vero  a| 
Stringa JSON contenente un timestamp che indica quando la licenza diventa valida. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| validUntilTimestamp | stringa | Vero  a| 
Stringa JSON contenente un timestamp che indica quando la licenza non è più valida. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| prodotto | stringa | Vero  a| 
Stringa JSON contenente la stringa del prodotto estratta dalla licenza. I valori definiti sono:

* Il contenuto della stringa non è convalidato dallo schema




| productVersion | stringa | Vero  a| 
Stringa JSON contenente la stringa della versione estratta dalla licenza. I valori definiti sono:

* Il contenuto della stringa non è convalidato dallo schema




| productSN | stringa | Vero  a| 
Stringa JSON contenente il numero di serie estratto dalla licenza. I valori definiti sono:

* Il contenuto della stringa non è convalidato dallo schema




| caratteristiche | stringa | Vero  a| 
Stringa JSON contenente il valore del pacchetto estratto dalla licenza. I valori definiti sono:

* Il contenuto della stringa non è convalidato dallo schema




| capacità | stringa | Vero  a| 
Stringa JSON contenente la capacità estratta dalla licenza.



| capacity2 | stringa | Vero  a| 
Stringa JSON contenente la capacità secondaria estratta dalla licenza.



| componenti aggiuntivi | vettore[link:#addons["componenti aggiuntivi"]] | Falso  a| 
Array JSON di oggetti JSON contenente l'elenco dei componenti aggiuntivi della licenza. Un componente aggiuntivo è una modifica alla licenza che potrebbe verificarsi in una data futura.



| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
elenco_metadati_tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| continuare | stringa | Falso  a| 



| conta | numero | Falso  a| 



| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====