---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-storagebackends-volumes.html 
summary: Elenca i volumi per un backend di archiviazione 
---
= Elenca i volumi per un backend di archiviazione
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/storageBackends/{storageBackend_id}/volumes`#

Restituisce un array JSON di tutte le risorse corrispondenti nella raccolta. Se nella richiesta vengono specificati singoli campi, l'array JSON degli elementi conterrà i campi richiesti per ciascuna risorsa corrispondente nell'ordine specificato.



[[parameters]]
== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| storageBackend_id | stringa | percorso | Vero  a| 
ID della risorsa storageBackend contenitore



| includi | stringa | query | Falso  a| 
Indica quali campi devono essere restituiti durante l'elenco di una raccolta.

Esempi di URL: "include=id", "include=id,name"

Esempi OpenAPI: "id"

* esempio: id,nome




| limite | stringa | query | Falso  a| 
Indica il numero massimo di risorse da restituire quando si elenca una raccolta.

Esempi di URL: "limit=2"

Esempi OpenAPI: "2"

|===


[[response]]
== Risposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| elementi | array[Qualsiasi tra: link:#volume_1_2_get_response_body["volume_1.2_get_response_body"], array[]] | Vero  a| 



| metadati | link:#type_astra_metadata_list["elenco_metadati_tipo_astra"] | Vero  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-volumes",
  "version": "1.2",
  "items": [
    [
      "24fe6e79-bf8d-45c9-96af-ef1d11fbd4a0",
      "myVolume"
    ],
    [
      "20a370f4-957f-446a-9126-08853d01933a",
      "secondVol"
    ],
    [
      "48e349a2-5bcd-4c59-896c-12b8240e634b",
      "smallVol"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Definizioni

.Vedi definizioni
[%collapsible]
====
[[additionalDetails]]
[role="api-collapsible-fifth-title"]
additionalDetails

[[type_astra_stateDetail]]
[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[[type_astra_metadata]]
[role="api-collapsible-fifth-title"]
type_astra_metadati

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema di metadati Astra


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Vero  a| 



| CreationTimestamp | stringa | Vero  a| 



| ModificationTimestamp | stringa | Vero  a| 



| CreatedBy | stringa | Vero  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[volume_1_2_get_response_body]]
[role="api-collapsible-fifth-title"]
volume_1.2_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-volume"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"
* "1,2"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Vero  a| 
Stringa JSON contenente il nome del volume. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 255




| stato | stringa | Falso  a| 
Stringa JSON contenente un valore che indica lo stato operativo del volume.



| dimensione | stringa | Falso  a| 
Stringa JSON contenente la dimensione del volume.



| usato | numero | Falso  a| 
Numero JSON contenente il numero di byte di quota utilizzati dal volume provisioned.



| usedPercentage | numero | Falso  a| 
Numero JSON contenente la percentuale di volume utilizzato.



| totale | numero | Falso  a| 
Numero JSON contenente il totale di byte dei volumi di cui è stato effettuato il provisioning.



| creationToken | stringa | Falso  a| 
Stringa JSON contenente il token di creazione del volume. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 255




| snapshotPossible | stringa | Falso  a| 
Stringa JSON che indica se il driver può eseguire uno snapshot del volume. I valori definiti sono:

* "vero" - Il driver può scattare un'istantanea del volume
* "falso" - Il driver non può acquisire un'istantanea del volume




| storageClass | stringa | Falso  a| 
Stringa JSON contenente la classe di archiviazione per il volume.

* I valori definiti sono:
* Lunghezza minima: 1
* Lunghezza massima: 255




| pvcName | stringa | Falso  a| 
Stringa JSON contenente il nome PersistentVolumeClaim (PVC) del volume.

* I valori definiti sono:
* Lunghezza minima: 1
* Lunghezza massima: 255




| internalName | stringa | Falso  a| 
Stringa JSON contenente il nome interno del volume sul cluster di storage di destinazione, se disponibile. Questo nome viene ottenuto dal driver CSI di Kubernetes.

* I valori definiti sono:
* Lunghezza minima: 1
* Lunghezza massima: 255




| appsUsing | array[string] | Vero  a| 
Array JSON di stringhe JSON, ciascuna contenente l'ID di un'applicazione che utilizza il volume. I valori definiti sono:

* Conforme allo schema identificativo Astra




| storageBackendID | stringa | Falso  a| 
Stringa JSON contenente l'ID del backend di archiviazione che fornisce il volume. I valori definiti sono:

* Conforme allo schema identificativo Astra




| orchestratore | stringa | Falso  a| 
Stringa JSON contenente l'orchestratore per questo volume. Questo sarà definito per i volumi Astra Data Store. I valori definiti sono:

* "trident" - Trident ha predisposto questo volume
* "vasa" - NetApp VASA Provider ha predisposto questo volume
* "altro" - Il volume è stato predisposto manualmente oppure l'orchestratore non è noto




| serviceLevel | stringa | Falso  a| 
Stringa JSON contenente la policy di qualità del servizio (QoS) definita per questo volume a livello di backend di storage. Questo sarà definito per i volumi Astra Data Store.



| exportPolicy | stringa | Falso  a| 
Stringa JSON contenente la policy di esportazione associata a questo volume. Questo sarà definito per i volumi Astra Data Store.



| nodeId | stringa | Falso  a| 
Stringa JSON contenente l'ID del nodo che gestisce il volume. Questo sarà definito per i volumi Astra Data Store. I valori definiti sono:

* Conforme allo schema identificativo Astra




| healthState | stringa | Falso  a| 
Stringa JSON contenente un valore che indica lo stato di salute del volume. Questo sarà definito per i volumi Astra Data Store. I valori definiti sono:

* "indeterminato" - Non è possibile determinare lo stato di salute della risorsa (ad esempio, a causa della mancanza di connettività)
* "normale" - La risorsa non presenta problemi noti e può fornire servizi in conformità con le specifiche dell'interfaccia
* "Avviso" - La risorsa presenta problemi noti che non le impediscono di fornire servizi in conformità con le specifiche dell'interfaccia
* "critico" - La risorsa presenta problemi noti che le impediscono di fornire servizi in conformità con le specifiche dell'interfaccia




| healthStateDetails | vettore[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Vero  a| 
Array JSON di oggetti JSON che elenca ulteriori dettagli sullo stato di salute attuale. Se non sono disponibili dettagli, questo array sarà vuoto.

* Elementi minimi: 0




| metadati | link:#type_astra_metadata["type_astra_metadati"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema di metadati Astra


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
elenco_metadati_tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| continuare | stringa | Falso  a| 



| conta | numero | Falso  a| 



| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====