---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-k8s-v1-apps-appbackups-appassets.html 
summary: 'Elenca le risorse dell"applicazione da un backup dell"applicazione per un"app' 
---
= Elenca le risorse dell'applicazione da un backup dell'applicazione per un'app
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appBackups/{appBackup_id}/appAssets`#

Restituisce un array JSON di tutte le risorse corrispondenti nella raccolta. Se nella richiesta vengono specificati singoli campi, l'array JSON degli elementi conterrà i campi richiesti per ciascuna risorsa corrispondente nell'ordine specificato.



[[parameters]]
== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| app_id | stringa | percorso | Vero  a| 
ID della risorsa dell'app che la contiene



| appBackup_id | stringa | percorso | Vero  a| 
ID della risorsa appBackup contenitore



| includi | stringa | query | Falso  a| 
Indica quali campi devono essere restituiti durante l'elenco di una raccolta.

Esempi di URL: "include=id", "include=id,name"

Esempi OpenAPI: "id"

* esempio: assetType,assetName




| limite | stringa | query | Falso  a| 
Indica il numero massimo di risorse da restituire quando si elenca una raccolta.

Esempi di URL: "limit=2"

Esempi OpenAPI: "2"

|===


[[response]]
== Risposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| elementi | array[Qualsiasi tra: link:#appAsset_1_1_get_response_body["appAsset_1.1_get_response_body"], array[]] | Vero  a| 



| metadati | link:#type_astra_metadata_list["elenco_metadati_tipo_astra"] | Vero  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appAssets",
  "version": "1.1",
  "items": [
    [
      "Pod",
      "mediawiki-69c6fcf864-2wx6l"
    ],
    [
      "ReplicaSet",
      "mediawiki-69c6fcf864"
    ],
    [
      "Service",
      "mediawiki"
    ],
    [
      "Deployment",
      "mediawiki"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Definizioni

.Vedi definizioni
[%collapsible]
====
[[GVK]]
[role="api-collapsible-fifth-title"]
GVK

Oggetto JSON contenente un gruppo/versione/tipo di Kubernetes.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| gruppo | stringa | Falso  a| 
Stringa JSON contenente un identificatore di gruppo assegnato da Kubernetes. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 254




| Tipo | stringa | Falso  a| 
Stringa JSON contenente un identificatore di tipo assegnato da Kubernetes. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 254




| versione | stringa | Falso  a| 
Stringa JSON contenente un identificatore di versione assegnato da Kubernetes. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 254


|===
[[type_json]]
[role="api-collapsible-fifth-title"]
tipo_json

Oggetto JSON contenente l'intero contenuto della definizione della risorsa Kubernetes.

[[labels]]
[role="api-collapsible-fifth-title"]
etichette

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Stringa JSON contenente il nome dell'etichetta I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* L'espressione regolare definita è: "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| valore | stringa | Vero  a| 
Stringa JSON contenente il valore dell'etichetta Definiti valori sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* L'espressione regolare definita è: "^([a-z0-9A-Z_.-]){1,63}$"


|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[[type_astra_metadata]]
[role="api-collapsible-fifth-title"]
type_astra_metadati

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema di metadati Astra


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Vero  a| 



| CreationTimestamp | stringa | Vero  a| 



| ModificationTimestamp | stringa | Vero  a| 



| CreatedBy | stringa | Vero  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[appAsset_1_1_get_response_body]]
[role="api-collapsible-fifth-title"]
appAsset_1.1_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "applicazione/astra-appAsset"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| assetType | stringa | Vero  a| 
Stringa JSON contenente un valore che indica il tipo di asset descritto, ottenuto da Kubernetes. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 254




| CreationTimestamp | stringa | Vero  a| 
Stringa JSON contenente un timestamp che indica quando sono stati creati i metadati di Kubernetes. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| GVK | link:#GVK["GVK"] | Vero  a| 
Oggetto JSON contenente un gruppo/versione/tipo di Kubernetes.



| risorsa | link:#type_json["tipo_json"] | Falso  a| 
Oggetto JSON contenente l'intero contenuto della definizione della risorsa Kubernetes.



| ID risorsa | stringa | Vero  a| 
Stringa JSON contenente un identificatore assegnato da Kubernetes. I valori definiti sono:

* Conforme allo schema identificativo Astra




| etichette | vettore[link:#labels["etichette"]] | Vero  a| 
Array JSON di oggetti JSON, ognuno dei quali contiene un'etichetta Kubernetes associata alla risorsa. Se non sono disponibili dettagli, questo array sarà vuoto.

* Elementi minimi: 0




| assetName | stringa | Vero  a| 
Stringa JSON contenente un nome assegnato da Kubernetes. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 254




| spazio dei nomi | stringa | Falso  a| 
Stringa JSON contenente un namespace assegnato da Kubernetes. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 254




| metadati | link:#type_astra_metadata["type_astra_metadati"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema di metadati Astra


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
elenco_metadati_tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| continuare | stringa | Falso  a| 



| conta | numero | Falso  a| 



| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====