---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-tasks-.html 
summary: 'Recupera un"attività' 
---
= Recupera un'attività
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/tasks/{task_id}`#

Restituisce la risorsa API Task memorizzata nel corpo della risposta JSON.



== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| task_id | stringa | percorso | Vero  a| 
ID della raccolta di attività da elencare

|===


== Risposta

[source]
----
Status: 200, Returns the stored Task API resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-task"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Vero  a| 
Stringa JSON contenente un nome gerarchico in notazione puntata (.) per l'attività. I valori definiti sono:

* Lunghezza minima: 3
* Lunghezza massima: 127
* L'espressione regolare definita è: "^(([a-z])_(\.))_([a-z])+$"




| riepilogo | stringa | Vero  a| 
Stringa JSON contenente il riepilogo in forma abbreviata dell'attività. I valori definiti sono:

* Lunghezza minima: 3
* Lunghezza massima: 63




| descrizione | stringa | Vero  a| 
Stringa JSON contenente una descrizione dell'attività. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 511




| servizio | stringa | Falso  a| 
Stringa JSON contenente il nome del servizio che gestisce l'attività. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| parentTaskID | stringa | Falso  a| 
Stringa JSON contenente un identificatore univoco globale dell'attività padre dell'attività. I valori definiti sono:

* Conforme allo schema identificativo Astra




| ID utente | stringa | Falso  a| 
Stringa JSON contenente l'ID utente associato a un'attività. Inclusa solo per le attività associate ad azioni avviate dall'utente. I valori definiti sono:

* Conforme allo schema identificativo Astra




| ID risorsa | stringa | Vero  a| 
Stringa JSON contenente un identificatore univoco globale della risorsa associata all'attività. I valori definiti sono:

* Conforme allo schema identificativo Astra




| URI della risorsa | stringa | Vero  a| 
Stringa JSON contenente l'URI associato all'attività. I valori definiti sono:

* Lunghezza minima: 3
* Lunghezza massima: 4095




| resourceCollectionURI | array[string] | Vero  a| 
Array JSON di stringhe JSON, ciascuna delle quali indica l'URL di accesso completamente espanso della risorsa associata all'attività. I valori definiti sono:

* Lunghezza minima: 3
* Lunghezza massima: 4095




| stato | stringa | Vero  a| 
Stringa JSON contenente un valore che indica lo stato operativo dell'attività. I valori definiti sono:

* "notStarted" - L'attività non è stata avviata.
* "in esecuzione" - L'attività è in esecuzione.
* "completato" - L'attività è stata completata.
* "pausing" - È stata richiesta la pausa dell'attività.
* "in pausa" - L'attività è in pausa.
* "annullamento" - È stata richiesta l'annullamento dell'attività.
* "annullato" - L'attività è stata annullata.
* "fallito" - L'attività non è riuscita.
* Lunghezza minima: 1
* Lunghezza massima: 31




| stateTransitions | vettore[link:#type_astra_stateTransition["tipo_transizione_stato_astra"]] | Vero  a| 
Array JSON di oggetti JSON, ognuno dei quali rappresenta l'insieme delle transizioni di stato consentite da un dato stato definito. Ogni oggetto JSON contiene i campi "from" e "to", dove il valore di "from" è il nome di uno stato e il valore di "to" è un array degli stati di destinazione consentiti.

* Lunghezza minima: 1
* Lunghezza massima: 31 Ad esempio: "stateTransitions" : [ { "from": "running", "to": ["paused", "cancelled"] }, { "from": "paused", "to": ["running", "cancelled"] }, ]




| stateDetails | vettore[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Vero  a| 
Array JSON di oggetti JSON che elenca dettagli aggiuntivi sullo "stato" corrente. Questo campo indica quando sono presenti condizioni o errori che impediscono allo stato effettivo di corrispondere allo stato desiderato. Se non sono disponibili dettagli, questo array sarà vuoto.

* Elementi minimi: 0




| orderHint | numero | Falso  a| 
Numero JSON che rappresenta l'ordine delle sottoattività. Questo campo può essere utilizzato dal client per ordinare le sottoattività dalla più piccola alla più grande.



| percentDone | numero | Falso  a| 
Numero JSON contenente la percentuale di completamento di un'attività in corso. Al termine dell'attività, questo valore viene impostato su "100".



| startTime | stringa | Falso  a| 
Stringa JSON contenente il timestamp che indica quando è iniziata l'attività. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| endTime | stringa | Falso  a| 
Stringa JSON contenente il timestamp che indica quando l'attività è terminata. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| cancelTime | stringa | Falso  a| 
Stringa JSON contenente il timestamp che indica quando l'attività è stata annullata. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| metadati | link:#type_astra_metadata["type_astra_metadati"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema di metadati Astra


|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-task",
  "version": "1.1",
  "id": "26e8e8ef-5549-5928-98dd-2c3d43a608e8",
  "name": "astra.backup.prep",
  "summary": "Backup preparation",
  "description": "Task to prepare for the application backup",
  "service": "nautilus",
  "userID": "abda967f-cd2c-4237-908e-99266648c553",
  "parentTaskID": "9cc8c321-6af1-406c-8158-2c6582c247f8",
  "resourceID": "626a0978-d55f-4841-8b7c-dc0c0f592c6f",
  "resourceURI": "/accounts/fdaa655c-15ab-4d34-aa61-1e9098e67be0/k8s/v1/apps/7c8bef49-697e-4fb4-810c-675cef4cf6c9/appSnaps/2b6dafc3-2172-4431-a482-6306b2703130",
  "resourceCollectionURI": [
    "/accounts/fdaa655c-15ab-4d34-aa61-1e9098e67be0/topology/v1/clouds/0df3f1a0-7203-4c12-aabf-a7bee6302671/clusters/dfd9de2d-6f0b-437b-a737-c8f7f176cd14/namespaces/f8b58091-4b9c-4c64-9b40-018dbaf7c5de/apps/f670bf11-8850-44bd-b330-815af6186a06/appSnaps/2b6dafc3-2172-4431-a482-6306b2703130",
    "/accounts/fdaa655c-15ab-4d34-aa61-1e9098e67be0/topology/v1/clouds/0df3f1a0-7203-4c12-aabf-a7bee6302671/clusters/dfd9de2d-6f0b-437b-a737-c8f7f176cd14/namespaces/923708f8-0435-45b5-8c00-fbdef3ffaf25/apps/f670bf11-8850-44bd-b330-815af6186a06/appSnaps/2b6dafc3-2172-4431-a482-6306b2703130"
  ],
  "state": "running",
  "stateTransitions": [
    {
      "from": "running",
      "to": [
        "paused",
        "cancelled"
      ]
    },
    {
      "from": "paused",
      "to": [
        "running",
        "cancelled"
      ]
    }
  ],
  "stateDetails": [],
  "orderHint": 0,
  "percentDone": 20.25,
  "startTime": "2020-08-06T12:24:52.256624Z",
  "endTime": "2020-08-06T12:26:52.256624Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_transizione_stato_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| da | stringa | Vero  a| 



| a | array[string] | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadati

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema di metadati Astra


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Vero  a| 



| CreationTimestamp | stringa | Vero  a| 



| ModificationTimestamp | stringa | Vero  a| 



| CreatedBy | stringa | Vero  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====