---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-managedclusters-storageclasses.html 
summary: Elenca le classi di archiviazione per un cluster gestito 
---
= Elenca le classi di archiviazione per un cluster gestito
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/managedClusters/{managedCluster_id}/storageClasses`#

Restituisce un array JSON di tutte le risorse corrispondenti nella raccolta. Se nella richiesta vengono specificati singoli campi, l'array JSON degli elementi conterrà i campi richiesti per ciascuna risorsa corrispondente nell'ordine specificato.



[[parameters]]
== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| ID cluster gestito | stringa | percorso | Vero  a| 
ID della risorsa managedCluster contenitore



| includi | stringa | query | Falso  a| 
Indica quali campi devono essere restituiti durante l'elenco di una raccolta.

Esempi di URL: "include=id", "include=id,name"

Esempi OpenAPI: "id"

* esempio: id,nome




| limite | stringa | query | Falso  a| 
Indica il numero massimo di risorse da restituire quando si elenca una raccolta.

Esempi di URL: "limit=2"

Esempi OpenAPI: "2"

|===


[[response]]
== Risposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| elementi | array[Qualsiasi tra: link:#storageClass_1_1_get_response_body["storageClass_1.1_get_response_body"], array[]] | Vero  a| 



| metadati | link:#type_astra_metadata_list["elenco_metadati_tipo_astra"] | Vero  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageClasses",
  "version": "1.1",
  "items": [
    [
      "e280ff62-be35-4f31-a31b-a210a1ad1b33",
      "my-storage-class"
    ],
    [
      "e8507dad-d33f-44b3-9c15-ec55ba6f6473",
      "standard"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidParams | vettore[link:#invalidParams["invalidParams"]] | Falso  a| 
Elenco dei parametri di query non validi

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Definizioni

.Vedi definizioni
[%collapsible]
====
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[[type_astra_metadata]]
[role="api-collapsible-fifth-title"]
type_astra_metadati

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema di metadati Astra


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Vero  a| 



| CreationTimestamp | stringa | Vero  a| 



| ModificationTimestamp | stringa | Vero  a| 



| CreatedBy | stringa | Vero  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[storageClass_1_1_get_response_body]]
[role="api-collapsible-fifth-title"]
storageClass_1.1_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "applicazione/astra-storageClass"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Vero  a| 
Stringa JSON contenente un valore che indica il nome della classe di archiviazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 255




| provisioner | stringa | Vero  a| 
Stringa JSON contenente un valore che indica il provisioner associato alla classe di archiviazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 255




| disponibile | stringa | Vero  a| 
Stringa JSON che indica se la classe di archiviazione è disponibile per il cluster o se è idonea ad essere aggiunta al cluster quando è in fase di gestione. I valori definiti sono:

* "disponibile" - La classe di archiviazione è disponibile per l'uso
* "idoneo" - La classe di archiviazione è idonea per essere utilizzata dal cluster quando è sotto gestione
* "non idoneo" - La classe di archiviazione non è idonea per essere utilizzata dal cluster quando è in gestione




| allowVolumeExpansion | stringa | Vero  a| 
Stringa JSON che indica se la classe di archiviazione consente l'espansione del volume. I valori definiti sono:

* "vero" - La classe di archiviazione consente l'espansione del volume
* "falso" - La classe di archiviazione non consente l'espansione del volume
* "non disponibile" - Non è noto se la classe di archiviazione consenta l'espansione del volume




| reclaimPolicy | stringa | Vero  a| 
Stringa JSON contenente un valore specifico del cloud che indica la politica di conservazione della classe di archiviazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 255




| volumeBindingMode | stringa | Vero  a| 
Stringa JSON contenente un valore specifico del cloud che indica la modalità di binding per la storage class. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 255




| isDefault | stringa | Falso  a| 
Stringa JSON che indica se la classe di archiviazione contiene l'annotazione predefinita. I valori definiti sono:

* "true" - La classe di archiviazione contiene l'annotazione predefinita




| maxSnapshotCount | numero | Falso  a| 
Numero JSON che indica quanti snapshot sono supportati. Queste informazioni sono allegate alle classi di storage fornite da NetApp.



| maxBackupCount | numero | Falso  a| 
Numero JSON che indica quanti backup sono supportati. Queste informazioni sono allegate alle classi di storage fornite da NetApp.



| prezzo | stringa | Falso  a| 
Stringa JSON che indica le unità di valuta per unità di tempo per la classe di archiviazione. Queste informazioni sono allegate alle classi di storage fornite da NetApp. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| valuta | stringa | Falso  a| 
Stringa JSON che indica il codice ISO 4217 a tre lettere della valuta in cui è misurato il prezzo. Queste informazioni sono associate alle classi di archiviazione fornite da NetApp. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 255




| prestazioni | numero | Falso  a| 
Numero JSON che indica l'obiettivo di livello di servizio (SLO) delle prestazioni in MBps. Queste informazioni sono allegate alle classi di storage fornite da NetApp.



| resilienza | stringa | Falso  a| 
Stringa JSON che indica la configurazione di resilienza per lo storage. Queste informazioni sono allegate alle classi di storage fornite da NetApp. I valori definiti sono:

* "regionale" - Il volume diventerà non disponibile se una determinata regione diventa non disponibile
* "multisito" - Il volume continuerà a essere disponibile se una determinata regione dovesse risultare non disponibile




| metadati | link:#type_astra_metadata["type_astra_metadati"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema di metadati Astra


|===
[[type_astra_metadata_list]]
[role="api-collapsible-fifth-title"]
elenco_metadati_tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| continuare | stringa | Falso  a| 



| conta | numero | Falso  a| 



| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
====