---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-k8s-v2-apps.html 
summary: Crea una nuova app 
---
= Crea una nuova app
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v2/apps`#

Indica i valori desiderati per la risorsa API dell'app da creare.



[[parameters]]
== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}


|===


[[request-body]]
== Corpo della richiesta

Indica i valori desiderati per la risorsa API dell'app da creare.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-app"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "2,0"
* "2,1"
* "2,2"




| nome | stringa | Vero  a| 
Stringa JSON contenente un nome per l'applicazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.
* Conforme allo schema di etichette DNS 1123




| clusterScopedResources | vettore[link:#clusterScopedResources["clusterScopedResources"]] | Falso  a| 
Array JSON di oggetti JSON che descrivono le risorse a livello di cluster che fanno parte di questa app



| namespaceScopedResources | vettore[link:#namespaceScopedResources["namespaceScopedResources"]] | Falso  a| 
Array JSON di oggetti JSON che descrivono le risorse che fanno parte di questa app



| namespaceMapping | vettore[link:#namespaceMapping["namespaceMapping"]] | Falso  a| 
Array JSON di oggetti JSON, ciascuno dei quali mappa uno spazio dei nomi di origine a uno spazio dei nomi di destinazione per un'operazione di clonazione. I valori definiti sono:

* Elementi minimi: 0




| storageClassMapping | vettore[link:#storageClassMapping["storageClassMapping"]] | Falso  a| 
Array JSON di oggetti JSON, ognuno dei quali mappa una classe di archiviazione di origine a una classe di archiviazione di destinazione per un'operazione di ripristino. Se non sono presenti elementi o se questi non sono presenti, verranno utilizzati i nomi originali delle classi di archiviazione di origine. I valori definiti sono:

* Elementi minimi: 0




| clusterID | stringa | Falso  a| 
Stringa JSON contenente l'ID del cluster su cui è in esecuzione l'applicazione. Non viene restituita se l'applicazione non è attualmente in esecuzione. Se specificato in fase di creazione, clusterID indica in quale cluster l'applicazione deve essere clonata. Se il cluster specificato non esiste, o se il cluster specificato non corrisponde al clusterID specificato nell'URI della richiesta, la clonazione non riuscirà. I valori definiti sono:

* Conforme allo schema identificativo Astra




| ID applicazione sorgente | stringa | Falso  a| 
Stringa JSON contenente l'ID di un'applicazione di origine. Viene restituita solo se l'applicazione è stata clonata da un'altra applicazione o è stata ripristinata da un backup o uno snapshot. Quando specificato in fase di creazione, il sourceAppID viene utilizzato insieme al sourceClusterID e indica quale applicazione in esecuzione verrà clonata. Se l'applicazione specificata non esiste sul cluster di origine, la clonazione non riuscirà. È possibile specificare solo uno tra sourceAppID, backupID o snapshotID durante la creazione di un'applicazione. I valori definiti sono:

* Conforme allo schema identificativo Astra




| sourceClusterID | stringa | Falso  a| 
Stringa JSON contenente l'ID del cluster su cui l'applicazione era precedentemente in esecuzione. Restituita solo se l'applicazione è stata clonata da un altro cluster. Quando specificato in fase di creazione, il sourceClusterID viene utilizzato insieme al sourceAppID e indica il cluster di origine dell'applicazione da clonare. Se il cluster di origine specificato non esiste, la clonazione non andrà a buon fine. I valori definiti sono:

* Conforme allo schema identificativo Astra




| backupID | stringa | Falso  a| 
Stringa JSON contenente l'ID del backup da cui è stata ripristinata l'applicazione. Restituita solo se l'applicazione è stata ripristinata da un backup. Se specificato in fase di creazione, backupID indica che un'applicazione verrà clonata da un backup esistente. Se il backup specificato non esiste, la clonazione non andrà a buon fine. È possibile specificare solo uno tra sourceAppID, backupID o snapshotID durante la creazione di un'applicazione. Se specificato in fase di sostituzione, backupID indica il backup dell'applicazione da cui verrà ripristinata l'applicazione sul posto. Se il backup specificato non esiste, il ripristino non andrà a buon fine. È possibile specificare solo uno tra backupID o snapshotID durante l'aggiornamento di un'applicazione. I valori definiti sono:

* Conforme allo schema identificativo Astra




| snapshotID | stringa | Falso  a| 
Stringa JSON contenente l'ID dello snapshot da cui è stata ripristinata l'applicazione. Restituita solo se l'applicazione è stata ripristinata da uno snapshot. Se specificato in fase di creazione, snapshotID indica che un'applicazione verrà clonata da uno snapshot esistente. Se lo snapshot specificato non esiste, la clonazione non andrà a buon fine. È possibile specificare solo uno tra sourceAppID, backupID o snapshotID durante la creazione di un'applicazione. Se specificato in fase di sostituzione, snapshotID indica lo snapshot dell'applicazione da cui verrà ripristinata l'applicazione sul posto. Se lo snapshot specificato non esiste, il ripristino non andrà a buon fine. È possibile specificare solo uno tra backupID o snapshotID durante l'aggiornamento di un'applicazione. I valori definiti sono:

* Conforme allo schema identificativo Astra




| restoreFilter | link:#restoreFilter["restoreFilter"] | Falso  a| 
Oggetto JSON contenente un elenco di filtri che descrivono quali risorse sono incluse o escluse da un'operazione di ripristino selettivo. Includi ed escludi si escludono a vicenda e un ripristino selettivo può utilizzare un solo tipo di filtro.



| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-app",
  "version": "2.2",
  "name": "jenkins",
  "clusterID": "0f284377-e5dc-4dcd-bacd-3197f2b8a347",
  "namespaceScopedResources": [
    {
      "namespace": "production"
    }
  ]
}
----
====


[[response]]
== Risposta

[source]
----
Status: 201, Returns the newly created app resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-app"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "2,0"
* "2,1"
* "2,2"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| collegamenti | vettore[link:#type_astra_link["type_astra_link"]] | Vero  a| 
Collegamenti che descrivono le operazioni supportate sulla risorsa.



| nome | stringa | Vero  a| 
Stringa JSON contenente un nome per l'applicazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.
* Conforme allo schema di etichette DNS 1123




| clusterScopedResources | vettore[link:#clusterScopedResources["clusterScopedResources"]] | Falso  a| 
Array JSON di oggetti JSON che descrivono le risorse a livello di cluster che fanno parte di questa app



| namespaceScopedResources | vettore[link:#namespaceScopedResources["namespaceScopedResources"]] | Vero  a| 
Array JSON di oggetti JSON che descrivono le risorse che fanno parte di questa app



| lastResourceCollectionTimestamp | stringa | Falso  a| 
Stringa JSON contenente il timestamp dell'ultima raccolta di risorse. Questo campo non è impostato se non è stata ancora eseguita alcuna raccolta di risorse per questa applicazione. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| stato | stringa | Vero  a| 
Stringa JSON contenente un valore che indica lo stato operativo dell'applicazione. I valori definiti sono:

* "in sospeso" - L'applicazione è programmata per la scoperta
* "scoperta" - L'applicazione è in fase di scoperta
* "Provisioning" - L'applicazione è in fase di provisioning
* "pronto" - L'applicazione è in esecuzione normalmente
* "fallito" - L'applicazione si trova in uno stato di errore permanente
* "Ripristino" - L'applicazione viene ripristinata da backup o snapshot
* "non disponibile" - L'applicazione non è attualmente accessibile
* "sconosciuto" - Non è possibile determinare lo stato dell'applicazione
* "eliminazione" - L'applicazione è in fase di eliminazione




| stateTransitions | vettore[link:#type_astra_stateTransition["tipo_transizione_stato_astra"]] | Falso  a| 
Array JSON di oggetti JSON, ognuno dei quali rappresenta l'insieme delle transizioni di stato consentite da un dato stato definito. Ogni oggetto JSON contiene i campi "from" e "to", dove il valore di "from" è il nome di uno stato e il valore di "to" è un array degli stati di destinazione consentiti.



| stateDetails | vettore[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Vero  a| 
Array JSON di oggetti JSON che elenca dettagli aggiuntivi sullo stato corrente, incluso il motivo per cui è stato raggiunto tale stato. Se non sono disponibili dettagli, questo array sarà vuoto. I valori definiti sono:

* Elementi minimi: 0




| protectionState | stringa | Vero  a| 
Stringa JSON contenente un valore che indica lo stato di protezione dell'applicazione. I valori definiti sono:

* "protetta" - L'applicazione ha una policy di protezione definita ed è conforme a tale policy
* "parziale" - L'applicazione ha una policy di protezione definita, ma non è conforme a tale policy
* "nessuno" - L'applicazione non ha una policy di protezione definita
* "atRisk" - La classe di archiviazione predefinita sul cluster non supporta gli snapshot, l'applicazione rischia di ottenere un volume non supportato




| protectionStateDetails | vettore[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Vero  a| 
Array JSON di oggetti JSON che elenca dettagli aggiuntivi sullo stato di protezione corrente, incluso il motivo per cui è stato raggiunto tale stato. Se non sono disponibili dettagli, questo array sarà vuoto. I valori definiti sono:

* Elementi minimi: 0




| appDetectedType | stringa | Falso  a| 
Stringa JSON che rappresenta in modo univoco il tipo specifico di applicazione rilevata. I valori definiti sono:

* "system" - L'applicazione contiene una risorsa che la identifica come parte dell'ambiente Kubernetes
* "acc" - L'applicazione contiene risorse che la identificano come un'istanza di Astra Control Center




| spazi dei nomi | array[string] | Vero  a| 
Array JSON di stringhe JSON contenenti i nomi degli spazi dei nomi in cui è in esecuzione l'applicazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 253
* Conforme allo schema di etichette DNS 1123




| namespaceMapping | vettore[link:#namespaceMapping["namespaceMapping"]] | Falso  a| 
Array JSON di oggetti JSON, ciascuno dei quali mappa uno spazio dei nomi di origine a uno spazio dei nomi di destinazione per un'operazione di clonazione. I valori definiti sono:

* Elementi minimi: 0




| storageClassMapping | vettore[link:#storageClassMapping["storageClassMapping"]] | Falso  a| 
Array JSON di oggetti JSON, ognuno dei quali mappa una classe di archiviazione di origine a una classe di archiviazione di destinazione per un'operazione di ripristino. Se non sono presenti elementi o se questi non sono presenti, verranno utilizzati i nomi originali delle classi di archiviazione di origine. I valori definiti sono:

* Elementi minimi: 0




| clusterName | stringa | Falso  a| 
Stringa JSON contenente il nome del cluster su cui è in esecuzione l'applicazione. Non viene restituita se l'applicazione non è attualmente in esecuzione.



| clusterID | stringa | Falso  a| 
Stringa JSON contenente l'ID del cluster su cui è in esecuzione l'applicazione. Non viene restituita se l'applicazione non è attualmente in esecuzione. Se specificato in fase di creazione, clusterID indica in quale cluster l'applicazione deve essere clonata. Se il cluster specificato non esiste, o se il cluster specificato non corrisponde al clusterID specificato nell'URI della richiesta, la clonazione non riuscirà. I valori definiti sono:

* Conforme allo schema identificativo Astra




| clusterType | stringa | Falso  a| 
Stringa JSON contenente un valore che indica il tipo di cluster. I valori definiti sono:

* "gke" - Kubernetes ospitato su Google Kubernetes Engine (GKE)
* "aks" - Kubernetes ospitato su Microsoft Azure Kubernetes Service (AKS)
* "eks" - Kubernetes ospitato su Amazon Elastic Kubernetes Service (Amazon EKS)
* "openshift" - Il cluster è di tipo OpenShift
* "kubernetes" - Il cluster è Kubernetes generico




| ID applicazione sorgente | stringa | Falso  a| 
Stringa JSON contenente l'ID di un'applicazione di origine. Viene restituita solo se l'applicazione è stata clonata da un'altra applicazione o è stata ripristinata da un backup o uno snapshot. Quando specificato in fase di creazione, il sourceAppID viene utilizzato insieme al sourceClusterID e indica quale applicazione in esecuzione verrà clonata. Se l'applicazione specificata non esiste sul cluster di origine, la clonazione non riuscirà. È possibile specificare solo uno tra sourceAppID, backupID o snapshotID durante la creazione di un'applicazione. I valori definiti sono:

* Conforme allo schema identificativo Astra




| sourceClusterName | stringa | Falso  a| 
Stringa JSON contenente il nome del cluster su cui l'applicazione era precedentemente in esecuzione. Restituita solo se l'applicazione è stata clonata da un altro cluster.



| sourceClusterID | stringa | Falso  a| 
Stringa JSON contenente l'ID del cluster su cui l'applicazione era precedentemente in esecuzione. Restituita solo se l'applicazione è stata clonata da un altro cluster. Quando specificato in fase di creazione, il sourceClusterID viene utilizzato insieme al sourceAppID e indica il cluster di origine dell'applicazione da clonare. Se il cluster di origine specificato non esiste, la clonazione non andrà a buon fine. I valori definiti sono:

* Conforme allo schema identificativo Astra




| backupID | stringa | Falso  a| 
Stringa JSON contenente l'ID del backup da cui è stata ripristinata l'applicazione. Restituita solo se l'applicazione è stata ripristinata da un backup. Se specificato in fase di creazione, backupID indica che un'applicazione verrà clonata da un backup esistente. Se il backup specificato non esiste, la clonazione non andrà a buon fine. È possibile specificare solo uno tra sourceAppID, backupID o snapshotID durante la creazione di un'applicazione. Se specificato in fase di sostituzione, backupID indica il backup dell'applicazione da cui verrà ripristinata l'applicazione sul posto. Se il backup specificato non esiste, il ripristino non andrà a buon fine. È possibile specificare solo uno tra backupID o snapshotID durante l'aggiornamento di un'applicazione. I valori definiti sono:

* Conforme allo schema identificativo Astra




| snapshotID | stringa | Falso  a| 
Stringa JSON contenente l'ID dello snapshot da cui è stata ripristinata l'applicazione. Restituita solo se l'applicazione è stata ripristinata da uno snapshot. Se specificato in fase di creazione, snapshotID indica che un'applicazione verrà clonata da uno snapshot esistente. Se lo snapshot specificato non esiste, la clonazione non andrà a buon fine. È possibile specificare solo uno tra sourceAppID, backupID o snapshotID durante la creazione di un'applicazione. Se specificato in fase di sostituzione, snapshotID indica lo snapshot dell'applicazione da cui verrà ripristinata l'applicazione sul posto. Se lo snapshot specificato non esiste, il ripristino non andrà a buon fine. È possibile specificare solo uno tra backupID o snapshotID durante l'aggiornamento di un'applicazione. I valori definiti sono:

* Conforme allo schema identificativo Astra




| replicationSourceAppID | stringa | Falso  a| 
Stringa JSON contenente l'ID dell'applicazione che viene replicata in questa applicazione. Viene restituita solo se l'applicazione è attualmente la destinazione in una relazione AppMirror e la relazione non è nello stato failedOver. Quando la relazione è nello stato failedOver, questo campo non viene restituito. I valori definiti sono:

* Conforme allo schema identificativo Astra




| restoreFilter | link:#restoreFilter["restoreFilter"] | Falso  a| 
Oggetto JSON contenente un elenco di filtri che descrivono quali risorse sono incluse o escluse da un'operazione di ripristino selettivo. Includi ed escludi si escludono a vicenda e un ripristino selettivo può utilizzare un solo tipo di filtro.



| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-app",
  "version": "2.2",
  "id": "39c1c79f-efab-5357-88fb-20e628c4dd96",
  "links": [],
  "name": "jenkins",
  "namespaceScopedResources": [
    {
      "namespace": "production",
      "labelSelectors": []
    }
  ],
  "state": "pending",
  "stateDetails": [],
  "protectionState": "none",
  "protectionStateDetails": [],
  "namespaces": [
    "production"
  ],
  "clusterName": "GKE-22",
  "clusterID": "0f284377-e5dc-4dcd-bacd-3197f2b8a347",
  "clusterType": "kubernetes",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


[[response]]
== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Definizioni

.Vedi definizioni
[%collapsible]
====
[[GVK]]
[role="api-collapsible-fifth-title"]
GVK

Oggetto JSON contenente un gruppo/versione/tipo di Kubernetes.

* Questo oggetto viene convalidato internamente rispetto ad Astra/apiResources.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| gruppo | stringa | Vero  a| 
Stringa JSON contenente un identificatore di gruppo assegnato da Kubernetes.

* Questa stringa viene convalidata internamente rispetto ad Astra/apiResources




| Tipo | stringa | Vero  a| 
Stringa JSON contenente un identificatore di tipo assegnato da Kubernetes.

* Questa stringa viene convalidata internamente rispetto ad Astra/apiResources




| versione | stringa | Vero  a| 
Stringa JSON contenente un identificatore di versione assegnato da Kubernetes.

* Questa stringa viene convalidata internamente rispetto ad Astra/apiResources


|===
[[clusterScopedResources]]
[role="api-collapsible-fifth-title"]
clusterScopedResources

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| GVK | link:#GVK["GVK"] | Vero  a| 
Oggetto JSON contenente un gruppo/versione/tipo di Kubernetes.

* Questo oggetto viene convalidato internamente rispetto ad Astra/apiResources.




| labelSelectors | array[string] | Falso  a| 
Array JSON di stringhe JSON che rappresentano un selettore di etichette per le GroupVersionKinds (GVK) a livello di cluster all'interno del cluster. Se questo è vuoto, allora tutte le istanze GVK presenti nel cluster sono incluse. Ogni elemento di questo array è una stringa di selettore di etichette Kubernetes e segue la stessa grammatica per tali valori. Esempi:

* [ "app=mysql" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore è mysql Altri esempi sono disponibili qui: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement[]


|===
[[namespaceScopedResources]]
[role="api-collapsible-fifth-title"]
namespaceScopedResources

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| spazio dei nomi | stringa | Vero  a| 
Stringa JSON contenente il nome di un namespace in cui è definita l'applicazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 253
* Conforme allo schema di etichette DNS 1123




| labelSelectors | array[string] | Falso  a| 
Array JSON di stringhe JSON che rappresentano un selettore di etichette all'interno del namespace. Se vuoto, vengono incluse tutte le risorse del namespace. Ogni elemento di questo array è una stringa di selettore di etichette Kubernetes e segue la grammatica per tali valori. Esempi:

* [ "app=mysql" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore è mysql
* [ "app != mysql" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore non è mysql
* [ "app in (mysql, mariadb)" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore è mysql o mariadb
* [ "app notin (nginx, wordpress)" ] -- Seleziona tutte le risorse che non hanno un'etichetta il cui nome è app e i cui valori sono nginx o wordpress
* [ "app" ] -- Seleziona tutte le risorse che hanno un'etichetta denominata app
* [ "!app" ] -- Seleziona tutte le risorse che non hanno un'etichetta denominata app Nota che è possibile includere più operatori di selezione in un singolo selettore, separati da virgole. In tal caso, i risultati dei singoli operatori di selezione vengono combinati con l'operatore AND:
* [ "app=mysql,version=2" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore è mysql e un'etichetta il cui nome è version e il cui valore è 2


|===
[[namespaceMapping]]
[role="api-collapsible-fifth-title"]
namespaceMapping

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| fonte | stringa | Vero  a| 
Stringa JSON contenente il nome del namespace sul cluster di origine. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 253
* Conforme allo schema di etichette DNS 1123




| destinazione | stringa | Vero  a| 
Stringa JSON contenente il nome del namespace sul cluster di destinazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 253
* Conforme allo schema di etichette DNS 1123


|===
[[storageClassMapping]]
[role="api-collapsible-fifth-title"]
storageClassMapping

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| fonte | stringa | Vero  a| 
Stringa JSON contenente il nome della classe di archiviazione di origine. Può anche essere '*' per specificare tutte le classi di archiviazione di origine. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Conforme allo schema di etichette DNS 1123 se viene utilizzato il nome della Storage Class
* '*' per specificare tutte le classi di archiviazione




| destinazione | stringa | Vero  a| 
Stringa JSON contenente il nome della classe di archiviazione di destinazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Conforme allo schema di etichette DNS 1123


|===
[[GVKN]]
[role="api-collapsible-fifth-title"]
GVKN

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| gruppo | stringa | Falso  a| 
Stringa JSON contenente un identificatore di gruppo assegnato da Kubernetes.

* Questa stringa viene convalidata internamente rispetto ad Astra/apiResources




| versione | stringa | Falso  a| 
Stringa JSON contenente un identificatore di versione assegnato da Kubernetes.

* Questa stringa viene convalidata internamente rispetto ad Astra/apiResources




| Tipo | stringa | Falso  a| 
Stringa JSON contenente un identificatore di tipo assegnato da Kubernetes.

* Questa stringa viene convalidata internamente rispetto ad Astra/apiResources




| spazi dei nomi | array[string] | Falso  a| 
Array JSON di stringhe JSON che descrivono i namespace da includere o escludere dalle risorse. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Conforme allo schema di etichette DNS 1123




| nomi | array[string] | Falso  a| 
Array JSON di stringhe JSON che descrivono i nomi delle risorse Kubernetes da includere o escludere dal ripristino selettivo. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 253
* Conforme allo schema di etichette DNS 1123




| labelSelectors | array[string] | Falso  a| 
Array JSON di stringhe JSON che descrivono i selettori di etichette Kubernetes utilizzati per includere o escludere risorse dal ripristino selettivo. Ogni elemento di questo array è una stringa di selettore di etichette Kubernetes e segue la stessa grammatica per tali valori. Esempi:

* [ "app=mysql" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore è mysql Altri esempi sono disponibili qui: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement[]


|===
[[restoreFilter]]
[role="api-collapsible-fifth-title"]
restoreFilter

Oggetto JSON contenente un elenco di filtri che descrivono quali risorse sono incluse o escluse da un'operazione di ripristino selettivo. Includi ed escludi si escludono a vicenda e un ripristino selettivo può utilizzare un solo tipo di filtro.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| resourceSelectionCriteria | stringa | Vero  a| 
Stringa JSON contenente un valore che indica come i filtri delle risorse selezionano le risorse. I valori validi sono include o exclude.



| GVKN | vettore[link:#GVKN["GVKN"]] | Vero  a| 
Array JSON di oggetti JSON che descrivono le risorse da filtrare durante un ripristino selettivo. Una risorsa corrisponde a un singolo elemento filtro GVKN se tutti i campi filtro specificati corrispondono al campo risorsa corrispondente. I campi filtro che sono array (ad esempio, namespaces e nomi) corrispondono se almeno uno dei loro elementi corrisponde al campo risorsa corrispondente. Il campo labelSelectors richiede che tutti i selettori corrispondano. Una risorsa che corrisponde a qualsiasi filtro nell'array di oggetti filtro GVKN viene inclusa o esclusa dal ripristino in base al valore resourceSelectionCriteria. Specificare oggetti GVKN vuoti comporta un errore di convalida.

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[targetSchema]]
[role="api-collapsible-fifth-title"]
targetSchema

[[accept-post]]
[role="api-collapsible-fifth-title"]
accept-post

[[accept-put]]
[role="api-collapsible-fifth-title"]
accetta-put

[[hints]]
[role="api-collapsible-fifth-title"]
suggerimenti

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| stato | stringa | Falso  a| 



| permettere | array[string] | Falso  a| 



| accept-post | link:#accept-post["accept-post"] | Falso  a| 



| autorizzazioni | array[string] | Falso  a| 



| accetta-put | link:#accept-put["accetta-put"] | Falso  a| 

|===
[[type_astra_link]]
[role="api-collapsible-fifth-title"]
type_astra_link

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| rel | stringa | Vero  a| 



| href | stringa | Vero  a| 



| tipo | stringa | Falso  a| 



| targetSchema | link:#targetSchema["targetSchema"] | Falso  a| 



| titolo | stringa | Falso  a| 



| suggerimenti | link:#hints["suggerimenti"] | Falso  a| 

|===
[[namespaceScopedResources]]
[role="api-collapsible-fifth-title"]
namespaceScopedResources

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| spazio dei nomi | stringa | Vero  a| 
Stringa JSON contenente il nome di un namespace in cui è definita l'applicazione. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 253
* Conforme allo schema di etichette DNS 1123




| labelSelectors | array[string] | Vero  a| 
Array JSON di stringhe JSON che rappresentano un selettore di etichette all'interno del namespace. Se vuoto, vengono incluse tutte le risorse del namespace. Ogni elemento di questo array è una stringa di selettore di etichette Kubernetes e segue la grammatica per tali valori. Esempi:

* [ "app=mysql" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore è mysql
* [ "app != mysql" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore non è mysql
* [ "app in (mysql, mariadb)" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore è mysql o mariadb
* [ "app notin (nginx, wordpress)" ] -- Seleziona tutte le risorse che non hanno un'etichetta il cui nome è app e i cui valori sono nginx o wordpress
* [ "app" ] -- Seleziona tutte le risorse che hanno un'etichetta denominata app
* [ "!app" ] -- Seleziona tutte le risorse che non hanno un'etichetta denominata app Nota che è possibile includere più operatori di selezione in un singolo selettore, separati da virgole. In tal caso, i risultati dei singoli operatori di selezione vengono combinati con l'operatore AND:
* [ "app=mysql,version=2" ] -- Seleziona tutte le risorse che hanno un'etichetta il cui nome è app e il cui valore è mysql e un'etichetta il cui nome è version e il cui valore è 2


|===
[[type_astra_stateTransition]]
[role="api-collapsible-fifth-title"]
tipo_transizione_stato_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| da | stringa | Vero  a| 



| a | array[string] | Vero  a| 

|===
[[additionalDetails]]
[role="api-collapsible-fifth-title"]
additionalDetails

[[type_astra_stateDetail]]
[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[[restoreFilter]]
[role="api-collapsible-fifth-title"]
restoreFilter

Oggetto JSON contenente un elenco di filtri che descrivono quali risorse sono incluse o escluse da un'operazione di ripristino selettivo. Includi ed escludi si escludono a vicenda e un ripristino selettivo può utilizzare un solo tipo di filtro.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| resourceSelectionCriteria | stringa | Falso  a| 
Stringa JSON contenente un valore che indica come i filtri delle risorse selezionano le risorse. I valori validi sono include o exclude.



| GVKN | vettore[link:#GVKN["GVKN"]] | Falso  a| 
Array JSON di oggetti JSON che descrivono le risorse da filtrare durante un ripristino selettivo. Una risorsa corrisponde a un singolo elemento filtro GVKN se tutti i campi filtro specificati corrispondono al campo risorsa corrispondente. I campi filtro che sono array (ad esempio, namespaces e nomi) corrispondono se almeno uno dei loro elementi corrisponde al campo risorsa corrispondente. Il campo labelSelectors richiede che tutti i selettori corrispondano. Una risorsa che corrisponde a qualsiasi filtro nell'array di oggetti filtro GVKN viene inclusa o esclusa dal ripristino in base al valore resourceSelectionCriteria. Specificare oggetti GVKN vuoti comporta un errore di convalida.

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[[invalidFields]]
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====