---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-credentials.html 
summary: Crea una nuova credenziale 
---
= Crea una nuova credenziale
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials`#

Indica i valori desiderati per la risorsa API Credential da creare.



== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}


|===


== Corpo della richiesta

Indica i valori desiderati per la risorsa API Credential da creare.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-credential"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"




| nome | stringa | Vero  a| 
Stringa JSON contenente un nome specificato dall'utente. Quando viene creata una credenziale per un utente, il nome verrà impostato sull'UUID di tale utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 127




| keyType | stringa | Falso  a| 
Stringa JSON contenente un descrittore del tipo di convalida dei dati facoltativo specificato dall'utente per il contenuto di keyStore. Vincoli di aggiornamento estesi:

* Se un elemento keyType non esiste nella risorsa e non è specificato in un aggiornamento, il keyType non deve continuare a esistere nella risorsa aggiornata.
* Se un keyType non esiste nella risorsa ed è specificato in un aggiornamento, il keyType deve essere aggiunto alla risorsa ed è necessario eseguire la convalida. Se la convalida fallisce, l'aggiornamento fallirà.
* Se un keyType esiste nella risorsa e non è specificato in un aggiornamento, il keyType deve essere conservato.
* Se un keyType esiste nella risorsa ed è specificato in un aggiornamento, e il keyType specificato corrisponde al keyType esistente, il keyType deve essere conservato.
* Se un keyType esiste nella risorsa ed è specificato in un aggiornamento, e il keyType specificato è diverso dall'esistente keyType, l'aggiornamento non andrà a buon fine. I valori definiti sono:
* "generico" - La credenziale è una raccolta generica di dati. Ciò equivale a non includere un keyType.
* La convalida estesa viene eseguita come segue:
* Una o più stringhe devono esistere nel keyStore.
* Ogni stringa nel keyStore deve avere un valore codificato in base64.
* "passwordHash" - La credenziale è un hash della password.
* La convalida estesa viene eseguita come segue:
* Il nome della credenziale deve essere univoco.
* Il nome della credenziale deve corrispondere a un ID risorsa utente valido.
* Il nome della credenziale non deve essere modificato.
* La risorsa utente corrispondente deve avere un "authProvider" di "local".
* Deve essere presente una stringa "in chiaro" all'interno del keyStore con un valore contenente una password in chiaro codificata in base64:
* La password in chiaro deve essere conforme alla policy relativa alle password dell'account.
* La password viene memorizzata come hash.
* All'interno del keyStore deve essere presente una stringa "change" con un valore contenente una stringa codificata in base64 "true" o "false".
* Una credenziale di tipo passwordHash può essere eliminata solo se l'ID utente indicato dal nome non esiste.
* "apikey" - La credenziale è una chiave API.
* La convalida estesa viene eseguita come segue:
* Una stringa "apikey" deve esistere all'interno del keyStore, con un valore contenente una stringa arbitraria codificata in base64.
* "kubeconfig" - La credenziale è un kubeconfig.
* La convalida estesa viene eseguita come segue:
* All'interno del keyStore deve essere presente una stringa "base64" con un valore contenente un file kubeconfig JSON codificato in base64.
* Il file kubeconfig deve descrivere un solo cluster.
* Non possono esistere altri campi all'interno del keyStore.
* "certificato" - La credenziale è un certificato codificato in formato PEM
* La convalida estesa viene eseguita come segue:
* All'interno di keyStore deve essere presente una stringa "certificate" con un valore contenente un certificato PEM codificato in base64.
* "privkey" - La credenziale è una chiave privata codificata in formato PEM.
* La convalida estesa viene eseguita come segue:
* All'interno del keyStore deve essere presente una stringa "privkey", con un valore contenente una chiave privata PEM codificata in base64.
* "s3" - Indica che le credenziali sono per l'accesso al servizio Simple Storage Service (S3).
* La convalida estesa viene eseguita come segue:
* Una stringa ""accessKey"" deve esistere all'interno del keyStore con un valore contenente una chiave di accesso S3 codificata in base64.
* Una stringa ""accessSecret"" deve esistere all'interno del keyStore con un valore contenente un segreto di accesso S3 codificato in base64.




| keyStore | link:#keyStore["keyStore"] | Vero  a| 
Oggetto JSON contenente stringhe JSON. Ogni stringa nel keyStore rappresenta una parte della credenziale. Il nome di ciascuna stringa rappresenta la parte della credenziale e la corrispondente coppia chiave-valore memorizza il valore di quella parte della credenziale in formato base64. I valori definiti sono:

* Conforme allo schema di dati codificati in base64. Non vengono imposti limiti alla lunghezza delle stringhe.




| valido | stringa | Falso  a| 
Stringa JSON che descrive se la credenziale è valida per l'uso. Il valore predefinito, se omesso, è "true". I valori definiti sono:

* "vero" - La credenziale è idonea all'uso.
* "falso" - La credenziale non deve essere utilizzata.




| validFromTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando la credenziale è valida. Queste vengono utilizzate per la rotazione delle credenziali. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| validUntilTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando la credenziale non è più valida. Queste vengono utilizzate per la rotazione delle credenziali. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credential",
  "version": "1.1",
  "name": "myCert",
  "keyStore": {
    "privKey": "SGkh",
    "pubKey": "VGhpcyBpcyBhbiBleGFtcGxlLg=="
  }
}
----
====


== Risposta

[source]
----
Status: 201, Returns the newly created credential resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-credential"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Vero  a| 
Stringa JSON contenente un nome specificato dall'utente. Quando viene creata una credenziale per un utente, il nome verrà impostato sull'UUID di tale utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 127




| keyType | stringa | Falso  a| 
Stringa JSON contenente un descrittore del tipo di convalida dei dati facoltativo specificato dall'utente per il contenuto di keyStore. Vincoli di aggiornamento estesi:

* Se un elemento keyType non esiste nella risorsa e non è specificato in un aggiornamento, il keyType non deve continuare a esistere nella risorsa aggiornata.
* Se un keyType non esiste nella risorsa ed è specificato in un aggiornamento, il keyType deve essere aggiunto alla risorsa ed è necessario eseguire la convalida. Se la convalida fallisce, l'aggiornamento fallirà.
* Se un keyType esiste nella risorsa e non è specificato in un aggiornamento, il keyType deve essere conservato.
* Se un keyType esiste nella risorsa ed è specificato in un aggiornamento, e il keyType specificato corrisponde al keyType esistente, il keyType deve essere conservato.
* Se un keyType esiste nella risorsa ed è specificato in un aggiornamento, e il keyType specificato è diverso dall'esistente keyType, l'aggiornamento non andrà a buon fine. I valori definiti sono:
* "generico" - La credenziale è una raccolta generica di dati. Ciò equivale a non includere un keyType.
* La convalida estesa viene eseguita come segue:
* Una o più stringhe devono esistere nel keyStore.
* Ogni stringa nel keyStore deve avere un valore codificato in base64.
* "passwordHash" - La credenziale è un hash della password.
* La convalida estesa viene eseguita come segue:
* Il nome della credenziale deve essere univoco.
* Il nome della credenziale deve corrispondere a un ID risorsa utente valido.
* Il nome della credenziale non deve essere modificato.
* La risorsa utente corrispondente deve avere un "authProvider" di "local".
* Deve essere presente una stringa "in chiaro" all'interno del keyStore con un valore contenente una password in chiaro codificata in base64:
* La password in chiaro deve essere conforme alla policy relativa alle password dell'account.
* La password viene memorizzata come hash.
* All'interno del keyStore deve essere presente una stringa "change" con un valore contenente una stringa codificata in base64 "true" o "false".
* Una credenziale di tipo passwordHash può essere eliminata solo se l'ID utente indicato dal nome non esiste.
* "apikey" - La credenziale è una chiave API.
* La convalida estesa viene eseguita come segue:
* Una stringa "apikey" deve esistere all'interno del keyStore, con un valore contenente una stringa arbitraria codificata in base64.
* "kubeconfig" - La credenziale è un kubeconfig.
* La convalida estesa viene eseguita come segue:
* All'interno del keyStore deve essere presente una stringa "base64" con un valore contenente un file kubeconfig JSON codificato in base64.
* Il file kubeconfig deve descrivere un solo cluster.
* Non possono esistere altri campi all'interno del keyStore.
* "certificato" - La credenziale è un certificato codificato in formato PEM
* La convalida estesa viene eseguita come segue:
* All'interno di keyStore deve essere presente una stringa "certificate" con un valore contenente un certificato PEM codificato in base64.
* "privkey" - La credenziale è una chiave privata codificata in formato PEM.
* La convalida estesa viene eseguita come segue:
* All'interno del keyStore deve essere presente una stringa "privkey", con un valore contenente una chiave privata PEM codificata in base64.
* "s3" - Indica che le credenziali sono per l'accesso al servizio Simple Storage Service (S3).
* La convalida estesa viene eseguita come segue:
* Una stringa ""accessKey"" deve esistere all'interno del keyStore con un valore contenente una chiave di accesso S3 codificata in base64.
* Una stringa ""accessSecret"" deve esistere all'interno del keyStore con un valore contenente un segreto di accesso S3 codificato in base64.




| valido | stringa | Vero  a| 
Stringa JSON che descrive se la credenziale è valida per l'uso. Il valore predefinito, se omesso, è "true". I valori definiti sono:

* "vero" - La credenziale è idonea all'uso.
* "falso" - La credenziale non deve essere utilizzata.




| validFromTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando la credenziale è valida. Queste vengono utilizzate per la rotazione delle credenziali. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| validUntilTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando la credenziale non è più valida. Queste vengono utilizzate per la rotazione delle credenziali. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credential",
  "version": "1.1",
  "id": "58e26f6a-a631-5122-8e0e-7afe306675c0",
  "name": "myCert",
  "valid": "true",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
keyStore

Oggetto JSON contenente stringhe JSON. Ogni stringa nel keyStore rappresenta una parte della credenziale. Il nome di ciascuna stringa rappresenta la parte della credenziale e la corrispondente coppia chiave-valore memorizza il valore di quella parte della credenziale in formato base64. I valori definiti sono:

* Conforme allo schema di dati codificati in base64. Non vengono imposti limiti alla lunghezza delle stringhe.


Mappatura hash delle stringhe in stringhe

[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====