---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/post-accounts-core-v1-groups-users.html 
summary: Creare un nuovo utente per un gruppo 
---
= Creare un nuovo utente per un gruppo
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/groups/{group_id}/users`#

Indica i valori desiderati per la risorsa API utente da creare.



== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| ID gruppo | stringa | percorso | Vero  a| 
ID della risorsa del gruppo contenitore

|===


== Corpo della richiesta

Indica i valori desiderati per la risorsa API utente da creare.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-user"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"
* "1,2"




| authID | stringa | Falso  a| 
Stringa JSON contenente l'identificativo associato a un provider di identità esterno. Il contenuto di questa stringa dipende da quanto specificato authProvider. Per un utente con "authProvider" come "local", "authID" è impostato sul valore di "email". Per un utente con "authProvider" come "ldap", "authID" è impostato sul suo Distinguished Name (DN) dal LDAP server.



| authProvider | stringa | Falso  a| 
Stringa JSON che indica il contesto dell'identificatore idAuth. I valori definiti sono:

* "cloud-central" - L'autenticazione dell'utente proviene dal servizio NetApp Cloud Central
* "locale" - L'autenticazione dell'utente proviene dall'archivio locale di utenti/password
* "ldap" - L'autenticazione dell'utente proviene da un LDAP server. In Astra Control Center, tutti gli utenti devono avere un valore "local" o "ldap". Se non viene specificato un valore, viene scelto il valore predefinito "local". In Astra Control Service, "authProvider" come "local" o "ldap" non è supportato. Se non viene specificato un valore, verrà utilizzato il valore predefinito "cloud-central".




| firstName | stringa | Falso  a| 
Stringa JSON contenente un nome proprio lungo specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| lastName | stringa | Falso  a| 
Stringa JSON contenente un cognome esteso specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| companyName | stringa | Falso  a| 
Stringa JSON contenente il nome dell'azienda associata all'utente. Se questa chiave non esiste, significa che non è stato fornito un nome di azienda. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| email | stringa | Vero  a| 
Stringhe JSON contenenti un indirizzo email specificato dall'utente.



| telefono | stringa | Falso  a| 
Stringa JSON contenente il numero di telefono dell'utente. Se questa chiave non esiste, significa che non è stato fornito un numero di telefono.



| postalAddress | link:#postalAddress["postalAddress"] | Falso  a| 
Oggetto JSON contenente una raccolta di campi che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutti e sei i campi contenuti. Se non è stato fornito nulla dall'utente, la stringa sarà vuota.



| sendWelcomeEmail | stringa | Falso  a| 
Stringa JSON che indica se verrà inviata un'e-mail di benvenuto dopo la convalida. Se non specificato in fase di creazione, il valore verrà impostato su "true" per ACS e su "false" per Astra Control Center. I valori definiti sono:

* "true" - Verrà inviata un'e-mail di benvenuto; valore predefinito alla creazione
* "false" - Non verrà inviata alcuna email di benvenuto Per un utente con "authProvider" come "local" o "ldap", questo valore viene ignorato e impostato su "false".




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-user",
  "version": "1.2",
  "firstName": "John",
  "lastName": "Doe",
  "email": "jdoe@example.com"
}
----
====


== Risposta

[source]
----
Status: 201, Returns the newly created user resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-user"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"
* "1,2"




| id | stringa | Vero  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| stato | stringa | Vero  a| 
Stringa JSON contenente un valore che indica lo stato operativo dell'utente. I valori definiti sono:

* "in sospeso" - L'account utente è in fase di creazione. L'utente può solo leggere e modificare la risorsa utente (valore predefinito).
* Questo stato non è valido per un utente con "authProvider" come "local"
* "attivo" - L'account utente è operativo (l'utente può accedere se l'impostazione dell'account "isEnabled" è "true").
* Questo è il valore predefinito per un utente con "authProvider" come "local"
* "sospeso" - L'account utente è sospeso (l'utente non può accedere indipendentemente dall'impostazione "isEnabled" dell'account).




| isEnabled | stringa | Vero  a| 
Stringa JSON che indica se l'utente è autorizzato ad accedere. I valori definiti sono:

* "true" - L'utente è autorizzato ad accedere; valore predefinito alla creazione.
* "false" - L'utente non è autorizzato ad accedere.




| authID | stringa | Falso  a| 
Stringa JSON contenente l'identificativo associato a un provider di identità esterno. Il contenuto di questa stringa dipende da quanto specificato authProvider. Per un utente con "authProvider" come "local", "authID" è impostato sul valore di "email". Per un utente con "authProvider" come "ldap", "authID" è impostato sul suo Distinguished Name (DN) dal LDAP server.



| authProvider | stringa | Falso  a| 
Stringa JSON che indica il contesto dell'identificatore idAuth. I valori definiti sono:

* "cloud-central" - L'autenticazione dell'utente proviene dal servizio NetApp Cloud Central
* "locale" - L'autenticazione dell'utente proviene dall'archivio locale di utenti/password
* "ldap" - L'autenticazione dell'utente proviene da un LDAP server. In Astra Control Center, tutti gli utenti devono avere un valore "local" o "ldap". Se non viene specificato un valore, viene scelto il valore predefinito "local". In Astra Control Service, "authProvider" come "local" o "ldap" non è supportato. Se non viene specificato un valore, verrà utilizzato il valore predefinito "cloud-central".




| firstName | stringa | Vero  a| 
Stringa JSON contenente un nome proprio lungo specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| lastName | stringa | Vero  a| 
Stringa JSON contenente un cognome esteso specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| companyName | stringa | Falso  a| 
Stringa JSON contenente il nome dell'azienda associata all'utente. Se questa chiave non esiste, significa che non è stato fornito un nome di azienda. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection




| email | stringa | Vero  a| 
Stringhe JSON contenenti un indirizzo email specificato dall'utente.



| telefono | stringa | Falso  a| 
Stringa JSON contenente il numero di telefono dell'utente. Se questa chiave non esiste, significa che non è stato fornito un numero di telefono.



| postalAddress | link:#postalAddress["postalAddress"] | Falso  a| 
Oggetto JSON contenente una raccolta di campi che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutti e sei i campi contenuti. Se non è stato fornito nulla dall'utente, la stringa sarà vuota.



| sendWelcomeEmail | stringa | Vero  a| 
Stringa JSON che indica se verrà inviata un'e-mail di benvenuto dopo la convalida. Se non specificato in fase di creazione, il valore verrà impostato su "true" per ACS e su "false" per Astra Control Center. I valori definiti sono:

* "true" - Verrà inviata un'e-mail di benvenuto; valore predefinito alla creazione
* "false" - Non verrà inviata alcuna email di benvenuto Per un utente con "authProvider" come "local" o "ldap", questo valore viene ignorato e impostato su "false".




| enableTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp in formato ISO-8601 che indica quando l'utente è stato abilitato per l'ultima volta. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| lastActTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp in formato ISO-8601 che indica quando l'API di identità è stata invocata l'ultima volta per conto di questo utente. (Nota: questa operazione è dispendiosa in termini di risorse.) I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Vero  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-user",
  "version": "1.2",
  "id": "5bad8e04-e2fd-5c43-98d7-300580993f49",
  "state": "pending",
  "isEnabled": "true",
  "authID": "HteLK3hk28sdbDLKHReB",
  "authProvider": "cloud-central",
  "firstName": "John",
  "lastName": "Doe",
  "email": "jdoe@example.com",
  "sendWelcomeEmail": "true",
  "lastActTimestamp": "2020-08-05T14:24:54.128427Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
postalAddress

Oggetto JSON contenente una raccolta di campi che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutti e sei i campi contenuti. Se non è stato fornito nulla dall'utente, la stringa sarà vuota.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| addressCountry | stringa | Vero  a| 
Stringa JSON contenente il nome o il codice del paese associato all'indirizzo postale, come specificato nello standard ISO 3166 Alpha-2. I valori definiti sono:

* Lunghezza minima: 2
* Lunghezza massima: 2




| addressLocality | stringa | Vero  a| 
Stringa JSON contenente la località (ad esempio, la città) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| addressRegion | stringa | Vero  a| 
Stringa JSON contenente la regione (ad esempio, stato) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| postalCode | stringa | Vero  a| 
Stringa JSON contenente il codice postale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| streetAddress1 | stringa | Vero  a| 
Stringa JSON contenente l'indirizzo stradale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| streetAddress2 | stringa | Falso  a| 
Stringa JSON contenente informazioni aggiuntive facoltative sull'indirizzo stradale, casella postale e così via. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63


|===
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====