---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-k8s-v1-apps-executionhooks-.html 
summary: 'Modificare un hook di esecuzione per un"app' 
---
= Modificare un hook di esecuzione per un'app
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHooks/{executionHook_id}`#

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* L'aggiornamento di un hook di esecuzione esistente avrà un impatto su tutte le azioni future delle applicazioni che utilizzano l'hook di esecuzione aggiornato.




== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| app_id | stringa | percorso | Vero  a| 
ID della risorsa dell'app che la contiene



| executionHook_id | stringa | percorso | Vero  a| 
ID della executionHook collection da elencare

|===


== Corpo della richiesta

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* L'aggiornamento di un hook di esecuzione esistente avrà un impatto su tutte le azioni future delle applicazioni che utilizzano l'hook di esecuzione aggiornato.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "applicazione/astra-executionHook"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | stringa | Falso  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Falso  a| 
Stringa JSON contenente un nome specificato dall'utente per la risorsa. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63 Il nome deve essere univoco in tutte le risorse execution hook.




| hookType | stringa | Falso  a| 
Stringa JSON che definisce il tipo di hook. I valori definiti sono:

* "netapp" - NetApp hook di esecuzione fornito.
* "personalizzato" - Collegato a uno specifico ID app. Le risorse hook di esecuzione con hookType "netapp" sono di sola lettura.




| matchingCriteria | vettore[link:#matchingCriteria["matchingCriteria"]] | Falso  a| 
Array JSON di oggetti JSON che descrivono i criteri di corrispondenza per l'hook di esecuzione. Quando vengono specificati più matchingCriteria, viene applicato un operatore logico AND ai criteri. I valori definiti sono:

* Elementi minimi: 0
* Numero massimo di elementi: 10




| azione | stringa | Falso  a| 
Stringa JSON che indica quale azione verrà eseguita dall'hook di esecuzione, presupponendo che i criteri di corrispondenza siano soddisfatti. I valori definiti sono:

* "istantanea"
* "backup"
* "ripristinare"
* "failover"




| fase | stringa | Falso  a| 
Stringa JSON che indica la fase dell'azione in cui verrà eseguito l'hook. I valori definiti sono:

* "pre" - L'hook di esecuzione verrà eseguito prima dell'azione specificata.
* "post" - L'hook di esecuzione verrà eseguito dopo l'azione specificata. I valori per l'azione "snapshot" sono "pre" e "post". I valori per l'azione "backup" sono "pre" e "post". Il valore per l'azione "restore" è "post". Il valore per l'azione "failover" è "post".




| hookSourceID | stringa | Falso  a| 
Stringa JSON contenente l'ID sorgente dell'hook che viene eseguito tramite questo hook di esecuzione. I valori definiti sono:

* Conforme allo schema identificativo Astra




| argomenti | array[string] | Falso  a| 
Array JSON di stringhe JSON per gli argomenti della sorgente. I valori definiti sono:

* Elementi minimi: 0
* Numero massimo di elementi: 16
* Lunghezza minima: 0
* Lunghezza massima: 127




| ID applicazione | stringa | Falso  a| 
Stringa JSON contenente l'ID associato dell'applicazione a cui è collegato questo hook. In sostanza, altri criteri di corrispondenza, se impostati. I valori definiti sono:

* Conforme allo schema identificativo Astra




| abilitato | stringa | Falso  a| 
Stringa JSON che indica se l'hook di esecuzione è abilitato. I valori definiti sono:

* "true" - L'hook di esecuzione è abilitato e verrà eseguito come specificato.
* "false" - L'hook di esecuzione è disabilitato e non verrà mai eseguito. Il valore predefinito è "true".




| descrizione | stringa | Falso  a| 
Stringa JSON contenente una descrizione specificata dall'utente per la sorgente dell'hook. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 511




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "arguments": [
    "freeze",
    "10"
  ]
}
----
====


== Risposta

[source]
----
Status: 204, Indicates if the executionHook resource was updated.
----


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Falso  a| 
Stringa JSON che identifica il tipo di criterio di corrispondenza.



| valore | stringa | Falso  a| 
Stringa JSON contenente un'espressione regolare da abbinare al tipo di corrispondenza specificato. Sintassi dell'espressione regolare: https://github.com/google/re2/wiki/Syntax[]

|===
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====