---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-upgrades-.html 
summary: Modificare un aggiornamento 
---
= Modificare un aggiornamento
:allow-uri-read: 
:imagesdir: ../media/


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/upgrades/{upgrade_id}`#

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* Gli aggiornamenti vengono programmati o eseguiti in base allo stato desiderato.




[[parameters]]
== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| upgrade_id | stringa | percorso | Vero  a| 
ID della raccolta di aggiornamenti da elencare

|===


[[request-body]]
== Corpo della richiesta

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* Gli aggiornamenti vengono programmati o eseguiti in base allo stato desiderato.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-upgrade"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"




| id | stringa | Falso  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| componentName | stringa | Falso  a| 
Stringa JSON contenente il nome del tipo di software che può essere aggiornato. I valori definiti sono:

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentInstance | stringa | Falso  a| 
Stringa JSON contenente l'URI del componente che può essere aggiornato. I valori definiti sono:

* Lunghezza minima: 3
* Lunghezza massima: 4095




| ID componente | stringa | Falso  a| 
Stringa JSON contenente un identificatore univoco globale del componente che può essere aggiornato. I valori definiti sono:

* Conforme allo schema identificativo Astra




| upgradeVersion | stringa | Falso  a| 
Stringa JSON contenente il SemVer del file immagine del software a cui è possibile eseguire l'aggiornamento. I valori definiti sono:

* Conforme allo SemVer Schema




| currentVersion | stringa | Falso  a| 
Stringa JSON contenente la versione corrente SemVer dell'entità da aggiornare. I valori definiti sono:

* Conforme allo SemVer Schema




| dipendenze | array[string] | Falso  a| 
Array JSON di stringhe JSON, ciascuna contenente l'UUID di un aggiornamento che deve essere completato prima che questo aggiornamento possa procedere. Utilizzato per determinare quali aggiornamenti verranno eseguiti come prerequisiti e in quale ordine. I valori definiti sono:

* Conforme allo schema identificativo Astra




| stato | stringa | Falso  a| 
Stringa JSON contenente un valore che indica lo stato operativo dell'aggiornamento. Se l'aggiornamento automatico è abilitato, gli aggiornamenti inizieranno nello stato "scheduled". Altrimenti, gli aggiornamenti inizieranno nello stato "proposed". I valori definiti sono:

* "non disponibile" - L'aggiornamento non è disponibile al momento
* "proposto" - L'aggiornamento è proposto ma non verrà eseguito automaticamente finché non verrà approvato
* "pianificato" - L'aggiornamento è stato approvato ma non è pronto per essere installato a causa di dipendenze, finestre temporali o risorse disponibili
* "in esecuzione" - L'aggiornamento è in corso
* "completato" - L'aggiornamento è stato completato
* "non riuscito" - L'aggiornamento non è stato completato




| stateDesired | stringa | Falso  a| 
Stringa JSON contenente un valore che indica lo stato desiderato per "state". Questo campo è incluso solo quando l'utente può richiedere direttamente una modifica dello stato della risorsa. I valori definiti sono:

* "proposto" - L'aggiornamento non è approvato e non deve essere eseguito
* "programmato" - L'aggiornamento è stato approvato e deve essere eseguito nella finestra temporale specificata
* "in esecuzione" - L'aggiornamento deve essere eseguito immediatamente, indipendentemente dalla finestra temporale




| stateDetails | vettore[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Array JSON di oggetti JSON che elenca dettagli aggiuntivi sullo "stato" corrente. Se non sono disponibili dettagli, questo array sarà vuoto.

* Elementi minimi: 0




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati Astra. Se non specificato durante l'aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-upgrade",
  "version": "1.1",
  "stateDesired": "running"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 204, Indicates if the upgrade resource was updated.
----


[[response]]
== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


[[response]]
== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


[[error]]
== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


[[definitions]]
== Definizioni

.Vedi definizioni
[%collapsible]
====
[[additionalDetails]]
[role="api-collapsible-fifth-title"]
additionalDetails

[[type_astra_stateDetail]]
[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[[type_astra_label]]
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[[type_astra_metadata_update]]
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati Astra. Se non specificato durante l'aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[[invalidParams]]
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[[invalidFields]]
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====