---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-subscriptions-.html 
summary: Modificare un abbonamento 
---
= Modificare un abbonamento
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/subscriptions/{subscription_id}`#

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* Se l'utente annulla l'abbonamento, l'endpoint PUT deve essere chiamato con "status": "inactive".
* Quando lo stato viene impostato su "inattivo", gli addebiti in sospeso per questo abbonamento vengono inviati a Zuora e l'abbonamento Zuora verrà contrassegnato come "inattivo" in qualche modo.




== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| subscription_id | stringa | percorso | Vero  a| 
ID della raccolta di abbonamenti da elencare

|===


== Corpo della richiesta

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* Se l'utente annulla l'abbonamento, l'endpoint PUT deve essere chiamato con "status": "inactive".
* Quando lo stato viene impostato su "inattivo", gli addebiti in sospeso per questo abbonamento vengono inviati a Zuora e l'abbonamento Zuora verrà contrassegnato come "inattivo" in qualche modo.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-subscription"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"
* "1,2"




| id | stringa | Falso  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| customerProfileID | stringa | Falso  a| 
La stringa JSON contenente l'ID del profilo del cliente da  http://authorize.net["Authorize.net"], che è stata richiamata dall'interfaccia utente, non è impostata per il periodo di prova. Restituisce una stringa vuota durante l'operazione di lettura, se non impostata. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63




| paymentFirstName | stringa | Falso  a| 
Stringa JSON contenente un nome proprio esteso specificato dall'utente, utilizzato per la fatturazione dei pagamenti. Specificato solo quando l'abbonamento viene rifatturato. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| paymentLastName | stringa | Falso  a| 
Stringa JSON contenente il cognome esteso specificato dall'utente, utilizzato per la fatturazione dei pagamenti. Specificato solo quando l'abbonamento viene rifatturato. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| paymentAddress | link:#paymentAddress["paymentAddress"] | Falso  a| 
Oggetto JSON contenente una raccolta di stringhe JSON che specificano un indirizzo di fatturazione. Specificato solo quando l'abbonamento viene rifatturato. Se questa chiave esiste, saranno presenti tutte e sei le stringhe JSON contenute. Se non è stato fornito nulla dall'utente, la stringa sarà vuota.



| paymentProfileID | stringa | Falso  a| 
Stringa JSON contenente l'ID del profilo di pagamento da  http://Authorize.net["Authorize.net"] che è stato richiamato dall'interfaccia utente, non impostato per il grace period. Restituisce una stringa vuota durante l'operazione di lettura se non impostato. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63




| paymentExpiry | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando il metodo di pagamento scade. Questo è ottenuto da authorize.net(http://authorize.net[] e viene impostato dall'interfaccia utente. I valori definiti sono:

* Conforme allo schema data/ora ISO-8601 Questo campo non viene restituito per i periodi di prova.




| purchaseOrderNumber | stringa | Falso  a| 
Stringa JSON contenente il numero dell'ordine di acquisto per il metodo di pagamento. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| marketplace | stringa | Falso  a| 
Stringa JSON che indica il marketplace per un account in cui verranno registrati i pagamenti. Valori definiti:

* "netapp"
* "azure"
* "aws"
* "gcp"




| licenseSN | stringa | Falso  a| 
Stringa JSON contenente il numero di serie della licenza per il metodo di pagamento. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| termini | stringa | Falso  a| 
Stringa JSON che indica il livello attuale dell'account. I valori definiti sono:

* "prova"
* "pagato"




| stato | stringa | Falso  a| 
Stringa JSON che indica lo stato attuale dell'abbonamento. I valori definiti sono:

* "attivo"
* "inattivo"




| appLimit | numero | Falso  a| 
Numero JSON che indica il limite di applicazioni per questo abbonamento. Il valore -1 indica nessun limite.



| namespaceLimit | numero | Falso  a| 
Numero JSON che indica il limite di namespace per questo abbonamento. Il valore -1 indica nessun limite.



| subscriptionPeriod | numero | Falso  a| 
Numero JSON che indica il periodo di abbonamento. Il valore -1 indica nessun limite. Unità: giorni



| gracePeriod | numero | Falso  a| 
Numero JSON che indica il grace period successivo alla scadenza del periodo di prova o all'annullamento di un abbonamento a pagamento. Unità: giorni



| reminderBeforePeriod | numero | Falso  a| 
Numero JSON che indica il numero di giorni prima della fine del periodo di prova in cui inizieranno le notifiche al cliente. Il valore è espresso in giorni con un valore di -1 che indica che non è applicabile.



| onboardStatus | stringa | Falso  a| 
Stringa JSON che indica lo stato attuale dell'onboarding del cliente. I valori validi sono "non avviato", "in corso", "riuscito", "fallito". I valori definiti sono:

* "non avviato"
* "in corso"
* "successo"
* "fallito"




| costPerAppUnit | numero | Falso  a| 
Numero JSON che indica il costo per unità dell'app. Per la versione di prova, il valore è 0. Unità: dollari statunitensi



| costPerNamespaceUnit | numero | Falso  a| 
Numero JSON che indica il costo per unità di namespace. Per la versione di prova, il valore è 0. Unità: dollari statunitensi



| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-subscription",
  "version": "1.2",
  "customerProfileID": "2157047189",
  "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
  "paymentExpiry": "2022-05-01T00:00:00Z"
}
----
====


== Risposta

[source]
----
Status: 204, Indicates if the subscription resource was updated.
----


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
paymentAddress

Oggetto JSON contenente una raccolta di stringhe JSON che specificano un indirizzo di fatturazione. Specificato solo quando l'abbonamento viene rifatturato. Se questa chiave esiste, saranno presenti tutte e sei le stringhe JSON contenute. Se non è stato fornito nulla dall'utente, la stringa sarà vuota.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| addressCountry | stringa | Vero  a| 
Stringa JSON contenente il nome o il codice del paese associato all'indirizzo postale, come specificato nello standard ISO 3166 Alpha-2. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 2




| addressLocality | stringa | Vero  a| 
Stringa JSON contenente la località (ad esempio, la città) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63




| addressRegion | stringa | Vero  a| 
Stringa JSON contenente la regione (ad esempio, stato) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63




| postalCode | stringa | Vero  a| 
Stringa JSON contenente il codice postale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63




| streetAddress1 | stringa | Vero  a| 
Stringa JSON contenente l'indirizzo stradale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63




| streetAddress2 | stringa | Falso  a| 
Stringa JSON contenente informazioni aggiuntive facoltative sull'indirizzo stradale, casella postale e altro. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 63


|===
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====