---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-.html 
summary: Modifica un account 
---
= Modifica un account
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}`#

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* La modifica di "isEnabled" da "false" a "true" imposta "enabledTimestamp" all'ora corrente.




== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della raccolta di account da elencare

* esempio: {{.Account}}


|===


== Corpo della richiesta

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* La modifica di "isEnabled" da "false" a "true" imposta "enabledTimestamp" all'ora corrente.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-account"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"




| id | stringa | Falso  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Falso  a| 
Stringa JSON contenente il nome dell'account. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.




| stato | stringa | Falso  a| 
Stringa JSON contenente un valore che indica lo stato operativo dell'account. I valori definiti sono:

* "in sospeso" - Le modifiche possono essere apportate solo alle risorse utente e ruolo dell'account (valore predefinito)
* "attivo" - È possibile apportare modifiche a qualsiasi risorsa dell'account
* "deletePending" - Gli utenti non possono accedere, le operazioni di protezione dei dati sono sospese, gli addebiti non maturano più




| isEnabled | stringa | Falso  a| 
Stringa JSON che indica che l'account è abilitato. I valori definiti sono:

* "falso" - Gli utenti non sono autorizzati a utilizzare questo account
* "vero" - Gli utenti sono autorizzati a utilizzare questo account




| enabledTimestamp | stringa | Falso  a| 
Stringa JSON contenente il timestamp che indica quando l'account è stato abilitato per l'ultima volta. Se l'account non è mai stato abilitato, questo campo è assente. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| accountContact | link:#accountContact["accountContact"] | Falso  a| 
Oggetto JSON contenente le informazioni di contatto dell'utente per creare un utente proprietario al momento dell'attivazione dell'account.



| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-account",
  "version": "1.0",
  "name": "frightened-pine"
}
----
====


== Risposta

[source]
----
Status: 204, Indicates if the account resource was updated.
----


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
postalAddress

Oggetto JSON contenente una raccolta di stringhe JSON che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutte e sei le stringhe JSON contenute. Se non si fornisce nulla, la stringa sarà vuota.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| addressCountry | stringa | Falso  a| 
Stringa JSON contenente il nome o il codice del paese associato all'indirizzo postale, come specificato nello standard ISO 3166 Alpha-2. I valori definiti sono:

* Lunghezza minima: 2
* Lunghezza massima: 2




| addressLocality | stringa | Falso  a| 
Stringa JSON contenente la località (ad esempio, la città) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| addressRegion | stringa | Falso  a| 
Stringa JSON contenente la regione (ad esempio, stato) associata all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| postalCode | stringa | Falso  a| 
Stringa JSON contenente il codice postale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| streetAddress1 | stringa | Falso  a| 
Stringa JSON contenente l'indirizzo stradale associato all'indirizzo postale. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| streetAddress2 | stringa | Falso  a| 
Stringa JSON contenente informazioni aggiuntive facoltative sull'indirizzo stradale, casella postale e altro. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63


|===
[role="api-collapsible-fifth-title"]
accountContact

Oggetto JSON contenente le informazioni di contatto dell'utente per creare un utente proprietario al momento dell'attivazione dell'account.

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| firstName | stringa | Falso  a| 
Stringa JSON contenente un nome proprio lungo specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.




| lastName | stringa | Falso  a| 
Stringa JSON contenente un cognome esteso specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.




| companyName | stringa | Falso  a| 
Stringa JSON contenente il nome dell'azienda associata all'utente. Se questa chiave non esiste, significa che non è stato fornito un nome di azienda. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63
* Questa stringa viene convalidata internamente per prevenire attacchi XSS, Unicode, directory traversal e SQL-injection.




| email | stringa | Falso  a| 
Stringhe JSON contenenti un indirizzo email specificato dall'utente. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63




| telefono | stringa | Falso  a| 
Stringa JSON contenente il numero di telefono dell'utente. Se questa chiave non esiste, significa che non è stato fornito un numero di telefono. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 31




| postalAddress | link:#postalAddress["postalAddress"] | Falso  a| 
Oggetto JSON contenente una raccolta di stringhe JSON che specificano un indirizzo. Se questa chiave non esiste, indica che non è stato fornito alcun indirizzo. Se questa chiave esiste, saranno presenti tutte e sei le stringhe JSON contenute. Se non si fornisce nulla, la stringa sarà vuota.

|===
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====