---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-certificates-.html 
summary: Modificare un certificato 
---
= Modificare un certificato
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/certificates/{certificate_id}`#

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito.

*Effetti collaterali*

* Un certificato CA aggiornato verrà aggiornato nell'archivio attendibile.
* Se un certificato CA attendibile esistente perde la sua attendibilità, verrà rimosso dall'archivio dei certificati attendibili.
* Se il corpo di un certificato viene aggiornato (campo "cert"), l'indicatore "isSelfSigned" deve essere incluso per indicare lo stato del nuovo certificato. Se l'indicatore "isSelfSigned" non è incluso in questo caso, il valore verrà impostato su "false".
* Se un aggiornamento non modifica il corpo del certificato (campo "cert"), l'indicatore "isSelfSigned" è facoltativo e il valore esistente verrà mantenuto se non specificato.




== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| ID certificato | stringa | percorso | Vero  a| 
ID della raccolta di certificati da elencare

|===


== Corpo della richiesta

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito.

*Effetti collaterali*

* Un certificato CA aggiornato verrà aggiornato nell'archivio attendibile.
* Se un certificato CA attendibile esistente perde la sua attendibilità, verrà rimosso dall'archivio dei certificati attendibili.
* Se il corpo di un certificato viene aggiornato (campo "cert"), l'indicatore "isSelfSigned" deve essere incluso per indicare lo stato del nuovo certificato. Se l'indicatore "isSelfSigned" non è incluso in questo caso, il valore verrà impostato su "false".
* Se un aggiornamento non modifica il corpo del certificato (campo "cert"), l'indicatore "isSelfSigned" è facoltativo e il valore esistente verrà mantenuto se non specificato.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "application/astra-certificate"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"
* "1,1"




| id | stringa | Falso  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| certUse | stringa | Falso  a| 
Stringa JSON che indica l'utilizzo del certificato. Se non specificato, il valore predefinito è "rootCA". I valori definiti sono:

* "rootCA" - Il certificato è un certificato di un'autorità di certificazione (CA) utilizzato per considerare attendibile qualsiasi certificato firmato da tale CA.
* "intermediateCA" - Il certificato è un certificato CA intermedio rilasciato da una CA radice.




| certificato | stringa | Falso  a| 
Stringa JSON contenente un certificato in formato PKCS-11 codificato in base64 (PEM). I valori definiti sono:

* Conforme allo schema di dati codificati in base64




| cn | stringa | Falso  a| 
Stringa JSON contenente un nome comune estratto dal certificato. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 511




| expiryTimestamp | stringa | Falso  a| 
Stringa JSON contenente un timestamp che indica quando il certificato scade. I valori definiti sono:

* Conforme allo schema di data e ora ISO-8601




| isSelfSigned | stringa | Falso  a| 
Stringa JSON che indica se il certificato è autofirmato. Se non specificato in fase di creazione, il valore predefinito è "false". In fase di aggiornamento:

* Se viene fornito un valore, questo verrà utilizzato.
* Se il valore non viene fornito e il campo "cert" è incluso nell'aggiornamento, il valore verrà impostato su "false".
* Se il valore non viene fornito e il campo "cert" non è incluso nell'aggiornamento, verrà mantenuto il valore esistente. I valori definiti sono:
* "vero" - Il certificato è autofirmato.
* "false" - Il certificato non è autofirmato.




| trustState | stringa | Falso  a| 
Stringa JSON contenente uno di un insieme di valori enumerati che indicano se il certificato è attendibile. I valori definiti sono:

* "non attendibile" - Il certificato non è attendibile.
* "attendibile" - Il certificato è contrassegnato come attendibile.
* "scaduto" - Il certificato è scaduto, quindi non è né attendibile né non attendibile.




| trustStateTransitions | vettore[link:#type_astra_stateTransition["tipo_transizione_stato_astra"]] | Falso  a| 
Array JSON di oggetti JSON, ognuno dei quali rappresenta l'insieme delle transizioni di stato consentite da un dato stato definito. Ogni oggetto JSON contiene i campi "from" e "to", dove il valore di "from" è il nome di uno stato e il valore di "to" è un array degli stati di destinazione consentiti.



| trustStateDesired | stringa | Falso  a| 
Stringa JSON contenente un valore che indica se il certificato è attendibile. Se non specificato in fase di creazione, il valore predefinito è "attendibile". I valori definiti sono:

* "non attendibile" - Il certificato non è attendibile.
* "attendibile" - Il certificato è contrassegnato come attendibile.




| trustStateDetails | vettore[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Array JSON di oggetti JSON che elenca ulteriori dettagli sullo stato di attendibilità del certificato. Se non sono disponibili dettagli, questo array sarà vuoto.

* Elementi minimi: 0




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-certificate",
  "version": "1.1",
  "trustStateDesired": "trusted"
}
----
====


== Risposta

[source]
----
Status: 204, Indicates if the certificate resource was updated.
----


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Risposta

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_transizione_stato_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| da | stringa | Vero  a| 



| a | array[string] | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====