---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-hooksources-.html 
summary: Modificare una sorgente di hook 
---
= Modificare una sorgente di hook
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/hookSources/{hookSource_id}`#

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* L'aggiornamento di un hook di origine esistente avrà un impatto immediato su tutte le future snapshot delle applicazioni che dispongono di hook di esecuzione corrispondenti che utilizzano la risorsa hook di origine aggiornata.
* Il checksum MD5 viene calcolato sul valore del campo "source" e impostato come valore del campo "sourceMD5Checksum".




== Parametri

[cols="5*"]
|===
| Nome | Tipo | In | Obbligatorio | Descrizione 


| ID account | stringa | percorso | Vero  a| 
ID della risorsa account contenitore

* esempio: {{.Account}}




| hookSource_id | stringa | percorso | Vero  a| 
ID della hookSource collection da elencare

|===


== Corpo della richiesta

Sostituisce l'intera risorsa memorizzata con il corpo della richiesta JSON fornito, preservando i valori chiave non modificabili dall'utente.

*Effetti collaterali*

* L'aggiornamento di un hook di origine esistente avrà un impatto immediato su tutte le future snapshot delle applicazioni che dispongono di hook di esecuzione corrispondenti che utilizzano la risorsa hook di origine aggiornata.
* Il checksum MD5 viene calcolato sul valore del campo "source" e impostato come valore del campo "sourceMD5Checksum".


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 
Tipo di media della risorsa. I valori definiti sono:

* "applicazione/astra-hookSource"




| versione | stringa | Vero  a| 
Versione della risorsa. I valori definiti sono:

* "1,0"




| id | stringa | Falso  a| 
Identificatore univoco globale della risorsa. I valori definiti sono:

* Conforme allo schema UUIDv4




| nome | stringa | Falso  a| 
Stringa JSON contenente un nome specificato dall'utente per la risorsa. I valori definiti sono:

* Lunghezza minima: 1
* Lunghezza massima: 63 Il nome deve essere univoco all'interno di tutte le risorse sorgente dell'hook.




| privato | stringa | Falso  a| 
Stringa JSON che indica se il campo sorgente verrà esposto nelle API o verrà lasciato intenzionalmente vuoto. I valori definiti sono:

* "true" - Il valore sorgente è privato e non verrà esposto tramite l'API.
* "false" - Il valore sorgente non è privato e verrà esposto tramite l'API.




| precaricato | stringa | Falso  a| 
Stringa JSON che indica se la sorgente è stata precaricata. I valori definiti sono:

* "vero" - La sorgente è stata precaricata.
* "false" - La sorgente non è stata precaricata. Le risorse sorgente hook precaricate sono di sola lettura.




| sourceType | stringa | Falso  a| 
Stringa JSON che definisce il tipo di origine dell'hook. I valori definiti sono:

* "script" - Script di shell. Il testo sorgente in chiaro non deve contenere dati binari o caratteri di ritorno a capo, altrimenti viene restituito un errore.




| fonte | stringa | Falso  a| 
Stringa JSON contenente lo script da eseguire in formato base64. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 131072
* Conforme allo schema di codifica dati base64. La dimensione massima di un valore sorgente è 128 KiB quando codificato utilizzando base64.




| sourceMD5Checksum | stringa | Falso  a| 
Stringa JSON contenente il checksum MD5 calcolato per il valore della chiave "source". I valori definiti sono:

* L'espressione regolare definita è: "^([0-9a-fA-F]){32}$"




| descrizione | stringa | Falso  a| 
Stringa JSON contenente una descrizione specificata dall'utente della sorgente dell'hook. I valori definiti sono:

* Lunghezza minima: 0
* Lunghezza massima: 511




| metadati | link:#type_astra_metadata_update["aggiornamento dei metadati di tipo Astra"] | Falso  a| 
Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


|===
.Esempio di richiesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-hookSource",
  "version": "1.0",
  "source": "ZWNobyAiVkhKaGJuTWdVbWxuYUhSeklRPT0iIHwgYmFzZTY0IC1k",
  "description": "Pre and post hook script for order processing v2"
}
----
====


== Risposta

[source]
----
Status: 204, Indicates if the hookSource resource was updated.
----


== Risposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Risposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Risposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 



| invalidFields | vettore[link:#invalidFields["invalidFields"]] | Falso  a| 
Elenco dei campi non validi del corpo della richiesta

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Risposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Risposta tipo
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Errore

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| tipo | stringa | Vero  a| 



| titolo | stringa | Vero  a| 



| dettaglio | stringa | Vero  a| 



| stato | stringa | Vero  a| 



| ID correlazione | stringa | Falso  a| 

|===
.Esempio di risposta di errore
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definizioni

.Vedi definizioni
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etichetta tipo_astra

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 



| valore | stringa | Vero  a| 

|===
[role="api-collapsible-fifth-title"]
aggiornamento dei metadati di tipo Astra

Metadati specificati dal client e dal servizio associati alla risorsa. I valori definiti sono:

* Conforme allo schema dei metadati di Astra. Se non specificato in fase di creazione, verrà creato un oggetto metadati senza etichette. Se non specificato in fase di aggiornamento, le etichette dell'oggetto metadati, creationTimestamp e createdBy, verranno conservate senza modifiche.


[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| etichette | vettore[link:#type_astra_label["etichetta tipo_astra"]] | Falso  a| 



| CreationTimestamp | stringa | Falso  a| 



| ModificationTimestamp | stringa | Falso  a| 



| CreatedBy | stringa | Falso  a| 



| modifiedBy | stringa | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del parametro di query non valido



| motivo | stringa | Vero  a| 
Motivo per cui il parametro di query non è valido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obbligatorio | Descrizione 


| nome | stringa | Vero  a| 
Nome del campo del corpo della richiesta non valido



| motivo | stringa | Vero  a| 
Motivo per cui il campo del corpo della richiesta non è valido

|===
====